### ISSUE TITLE
Filetransfer question

### ISSUE THREAD

**Issue by lukanus** [lucas-clemente/quic-go#1180]
Hi! 
I created a simple benchmark on my localhost for simple PUT request with 1GB file using different variations of example code. Filetranster from Client to Server. 
Surprisingly transfer of QUIC / HTTP 2  (using pretty much the same code) took much much longer than TCP over HTTP 1 .   Around 47s vs 8s. 
Why it is so slow? Is there anything I might be doing wrong or lack its of traliers support in RoundTrip function in h2quic. Or maybe it should create multiple parallel streams to send data more efficiently? 
I need something like that, and I'm happy to help rather than writing my own implementation of UDT myself

**Comment by marten-seemann** [comment]
The general trend of this is expected. Bulk file transfer on localhost is not the condition that QUIC is optimized for, although I'm a bit surprised that the difference is that big. You could try to increase the flow control window in the `quic.Config` and see if that has any effect.

QUIC will give you an advantage over TCP if your application makes use of multiple streams (because it avoids head-of-line blocking), especially on "bad" connections (packet loss and long RTT, although our loss recovery still has some known problems on lossy connections).

I ran some benchmarks recently when I implemented packet pacing, and the results might be interesting for you: https://github.com/lucas-clemente/quic-go/pull/1108. What I'm measuring in these benchmarks is the upload of a 50 MB file, once over TCP, then from a Chrome to a quic-go server, and from a quic-go client to a quic-go server. As you can see, we're getting in the order of magnitude of TCP (which is probably all that we can hope for. Even Google's QUIC implementation is slower than TCP for bulk data transfer).

**Comment by lukanus** [comment]
@marten-seemann Asking, because "in theory" lack of TCP ACKs in UDP, filetransfer should be like two times faster. Especially that I'm using the same code. 
Added few more tests - it seems that I was using http 1.11 for TCP, forcing http2 support for client makes it even faster.

So - for some reason 
`map[Accept-Encoding:[gzip] User-Agent:[quic-go]] &{PUT /test1 HTTP/2.0 2 0 map[Accept-Encoding:[gzip] User-Agent:[quic-go]] 0xc42016c2e0 <nil> 0 [] false fq-test.com map[] map[] <nil> map[] 127.0.0.1:60148 /test1 0xc4202e0000 <nil> <nil> 0xc42017a0c0}` takes 23.868315933.s
and :
 `map[User-Agent:[Go-http-client/2.0] Accept-Encoding:[gzip]] &{POST /test1 HTTP/2.0 2 0 map[Accept-Encoding:[gzip] User-Agent:[Go-http-client/2.0]] 0xc420011f80 <nil> -1 [] false fq-test.com map[] map[] <nil> map[] 127.0.0.1:51602 /test1 0xc4202622c0 <nil> <nil> 0xc42005ea80}`
precisely 4.823221682s. 

Making http2 over tcp 5 times faster over lo interfece . 

Either something is really wrong, or I'm not using it correctly. 
Receive function is dead simple: 
`func test(w http.ResponseWriter, r *http.Request) {
	uid := uuid.NewV4()
	a, _ := os.Create("./" + uid.String())
	defer a.Close()
	io.Copy(a, r.Body)
}`
I'm wondering isn't that a problem with sending this over one stream? 
However TCP 1.11 should also work in similar way. So it should not be a issue. 
Maybe something with buffering of r.Body before io.Copy() then ?

As I said before - I'm happy to help with that, but don't quite know where to start.

**Comment by marten-seemann** [comment]
> @marten-seemann Asking, because "in theory" lack of TCP ACKs in UDP, filetransfer should be like two times faster. Especially that I'm using the same code.

This is not correct, and I have no idea why QUIC would be twice as fast as TCP in theory.

> Making http2 over tcp 5 times faster over lo interfece .
>
> Either something is really wrong, or I'm not using it correctly.

As I said before, I'm not optimizing quic-go for maximum transfer speed on a local interface. You won't get any benefit from using the QUIC protocol over the TCP protocol, no matter which implementation you use. QUIC shines for applications that use multiple streams under realistic conditions (packet loss and non-zero RTT).
