### ISSUE TITLE
Fix goreportcard issues to allow inclusion in avelino/awesome-go repository

### ISSUE THREAD

**Issue by lthibault** [lucas-clemente/quic-go#1181]
I've taken the liberty of submitting quic-go for inclusion in http://github.com/avelino/awesome-go (see issue [here](https://github.com/avelino/awesome-go/pull/1786#issuecomment-364131297)).

The only thing that is required at this time is for the issues reported by quic-go's [goreportcard](http://goreportcard.com/report/github.com/lucas-clemente/quic-go) to be resolved.

I'm more than happy to lend a hand, but don't want to begin working on a PR unless you fine folks are actually interested 😄.

**Comment by marten-seemann** [comment]
Thanks for nominating us! Would be cool to be included in that list!

These guys seem to have pretty strict criteria (we already have an A+...), but it's mostly stuff that we should fix anyway. From your PR I get that they only care about gofmt, ineffassign and golint:

- gofmt: I ran that locally and the suggested changes look reasonable.
- ineffassign: we should fix these.
- golint: mostly looks like stuff we should fix.
  - Fixing the variable names in the congestion packet is something we can do. The reason we're not using the idiomatic naming scheme there is that we translated the Chrome's congestion code from C++ to Go when we implement congestion control (I know, bad excuse).
  - There is one point I kind of disagree with, the dot import in the test. Using dot imports is the [recommended way of using Ginkgo](http://onsi.github.io/ginkgo/#bootstrapping-a-suite)). On the other hand, golint only complains for non-testing files, so this effects only two files or so. There'd be value in fixing this as well, since we'd be able to run golint in our CI builds then.

I'd appreciate a PR for this, if you want to work on this. To make reviewing easier, please split the PR up into a few commits.

**Comment by marten-seemann** [comment]
@lthibault Thanks again for reporting. I fixed all issues raised by gofmt, ineffassign and golint that I considered worth fixing. Let's see if they're willing to include quic-go now.

**Comment by lthibault** [comment]
Hi Marten,

Thanks for letting me know, I’m happy to have been able to help.  Thanks very much for all your work on this fantastic library (and pass my thanks along to Lucas as well) !

Best,
Louis
