### ISSUE TITLE
Check appends and slice allocations for DOS problems

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#123]

**Comment by lucas-clemente** [comment]
I've gone through all `make`s and `append`s, and fixed a couple of possible DOSes.

I've not looked at the loops for the NACK range calculations, since they will get removed soonish.

@marten-seemann: Should we close this issue, or do you want to have another look?

**Comment by marten-seemann** [comment]
NACK range calculations should not be a problem, since the maximum number of NACK ranges we receive is limited by *MaxPacketSize*, at least for each packet. Not really sure what happens with truncated ACKs, but I guess congestion control will then save us from getting DOSed.
Anyway, let's think about that in detail when implementing QUIC 34. Closing this issue for now.
