### ISSUE TITLE
Default max CWND and receive buffer size

### ISSUE THREAD

**Issue by shinichikudo987** [lucas-clemente/quic-go#1280]
Hi all,

I am running some experiments using quic-go. I found some parameters in  quic-go/internal/protocol/server_parameters.go and  quic-go/internal/congestion/cubic.go, but I don't know the mean of their parameters. Any body can clarify me?

Is DefaultMaxCongestionWindow similar to kDefaultMaxCongestionWindowPackets in src/net/quic/core/congestion_control/send_algorithm_interface.h of chromium?
Which parameters in quic-go is similar to default receiver buffer size in chromium?
Do Default Cubic backoff factor affect on Congestion Window and buffer size?

Thank you in advance!

**Comment by marten-seemann** [comment]
Our congestion controller is **very** similar to the one used in Chromium, since we translated the Chromium code to Go when we first implemented congestion control in quic-go.

You can find all the congestion related code in https://github.com/lucas-clemente/quic-go/tree/master/internal/congestion, if you want to look up what a specific parameter is exactly doing.

**Comment by shinichikudo987** [comment]
Thank for your response.
