### ISSUE TITLE
downloads failing when CloseAfterFirstRequest is set

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#135]
Try downloading a 50 MB file.

**Comment by marten-seemann** [comment]
Increasing the timeout in `h2quic.Server.handleRequest`to 500ms seems to solve the problem, at least on loopback.

**Comment by lucas-clemente** [comment]
This probably happens when there are too many frames queued for sending, and they don't get sent out in the 100ms interval. Since `CloseAfterFirstRequest` is only for the demo (where we don't have large downloads), I don't mind it much. If you want, change it to 500ms, although it won't really affect anything.
