### ISSUE TITLE
Updating to latest quic-go pulls in a testing framework

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#1353]
In the process of releasing a Caddy update, I was updating our vendored quic-go dependency but I realized that it pulled in a LOT of new dependencies, including ginkgo and gomega, which I believe shouldn't be pulled in except for tests? (I was not using `-t`, so it shouldn't pull in test dependencies.) I admit I am in the middle of some other things so I haven't investigated where they are used in the code.

Before I commit 340+ new files to our repo, I decided to defer updating quic-go for now until we figure out if this is in error (instead of delaying the Caddy release entirely). If it is a mistake, great -- we can get it fixed. If not, then can we find a way not require test frameworks for production builds?

Any way to lighten the dependency tree at this point would be greatly appreciated.

PS. I would be remiss to omit another thank-you for this project. You guys are doing great work.

**Comment by marten-seemann** [comment]
Hi @mholt, it would be great if you can hold off the release for another half an hour or so. I'd like to see the recent fixes (especially #1340) included in the next Caddy release. 
ginkgo and gomega should definitely not be needed anywhere else than in the test code. I'm investigating right now.

**Comment by marten-seemann** [comment]
Update: I think the culprit is https://github.com/lucas-clemente/quic-go/blob/master/integrationtests/tools/testserver/server.go. The whole *integrationtests* directory only contains test code, and doesn't need to be vendored. But afaik, it's not possible to exclude directories from being vendored, is it?

**Comment by mholt** [comment]
I'm using `gvt` to manage the vendor folder -- it should only pull in dependencies that are needed to compile, not test (unless `-t` is used). I wonder if it has something to do with the dot-imports? 

https://github.com/lucas-clemente/quic-go/blob/240896a4dd6fc56c42698bb0855166858c47fa27/integrationtests/tools/testserver/server.go#L15-L16

I'm not sure though, it's just a guess.

And no, I'm not sure of a way to prevent a subfolder from being vendored.

If the files all end with `_test.go`, that should do it; because there's nothing about the folder or file structure as-is that would cause them to be treated as test-only. (There might also be a provision for a `testdata` folder? Worth looking into.)

I'll hold the release for a few more hours. It's after midnight here, so I'm gonna get some sleep and return to this in the morning. :+1:

**Comment by marten-seemann** [comment]
Thanks, @mholt!

I tried two things:
* replace the dot imports by normal imports
* rename the *integrationtests* directory to *integration_test* (hoping that Go would recognize that)

Both attempts don't work. `gvt` still vendors ginkgo.

@lucas-clemente: Any ideas?

**Comment by mholt** [comment]
@marten-seemann I'm gonna release Caddy 0.11 today but we can get quic-go updated on the next release; I have a bunch of PRs in the backlog I need to go through anyway. :+1:

**Comment by marten-seemann** [comment]
Having thought about this, I don’t really see what a good solution would be. 
The only thing that would actually get rid of the ginkgo files would be moving the integrationtests directory in another repo, but that would create a strong coupling between those two repos, so I’d like to avoid that.

**Comment by mholt** [comment]
I will have a similar dilemma with Caddy as I plan to build out its testing suite, but I think the tests will live in a separate repo, since the test suite really is a different application entirely. I don't think it's bad to have to repos, personally...

**Comment by marten-seemann** [comment]
Hello @mholt, I recently discussed this issue with @lucas-clemente. We both agree that splitting the integration tests into a separate repository will complicate things quite a bit, since we're often adding new integration tests when fixing a bug.

I see the fact that govendor doesn't have an option to ignore certain directories is a shortcoming of the go tooling itself. On the other hand, while aesthetically unsatisfying, this shouldn't have any effect on the Caddy binary, since ginkgo and gomega are only used for the test code, and therefore won't be compiled when building the regular binary. 
I haven't had the time to take a closer look at the vgo changes coming up with Go 0.11, but I hope that will finally solve the problem.

**Comment by mholt** [comment]
Hey Marten! Nice to hear an update about this. :) Thanks for looking into it.

My main concern isn't so much binary size (although that is mildly a concern, but not something this library really contributes to in a significant way) -- it's the size of the code repository.

I will take another look and see if we can get away without vendoring those particular packages and manually wrangle the vendor folder a bit, to work around the issue in the meantime.

**Comment by marten-seemann** [comment]
Closing this issue since it seems there's nothing more I can do about it.
