### ISSUE TITLE
Make MaxIncomingStreams Unlimited

### ISSUE THREAD

**Issue by pigeon1990** [lucas-clemente/quic-go#1495]
Hello,
Is it possible to make MaxIncomingStreams unlimited? Thank you very much.

**Comment by marten-seemann** [comment]
The value sent in the Transport Parameters (see https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.6.6.1) is currently a uint16, so that's the limit we're using in the `quic.Config`. It would be possible to use a higher value, if quic-go implemented a mechanism to increase this value right after the handshake completes.
Note that this value does **not** limit the number of streams you can use over the lifetime of a connection, it's just the maximum number of incoming streams **at the same time**.

This limit is a DoS protection, because it prevents the peer from opening a huge number of streams (where every stream consumes a certain amount of memory).

**Comment by pigeon1990** [comment]
Is it possible to post different data to the server concurrently, using the same client as this
```golang
package main

import (
	"fmt"
	"net/http"
	"strings"
	"sync"

	"github.com/lucas-clemente/quic-go/h2quic"
)

func main() {
	client := &http.Client{
		Transport: &h2quic.RoundTripper{},
	}

	wg := &sync.WaitGroup{}
	for i := 0; i < 100; i++ {
		go post(client, wg)
	}
	wg.Wait()
	fmt.Println("done")
}
func post(client *http.Client, wg *sync.WaitGroup) {
	wg.Add(1)
	res, err := client.Post("https://localhost:4242/entry", "application/json", strings.NewReader("some data"))
	if err != nil {
		panic(err)
	}
	defer res.Body.Close()
	defer wg.Done()
}
````
Looking forward to any Suggestions
