### ISSUE TITLE
Flow control deadlock when using SetReadDeadline / CancelRead

### ISSUE THREAD

**Issue by ltucker** [lucas-clemente/quic-go#1545]
Example:
https://gist.github.com/ltucker/c03d3d917b17cd31bcf4c5ab73638657

Typical Output:
https://gist.github.com/ltucker/1d2d8c28f2976077cddace06da666080

I've been running into what appears to be a flow control related deadlock on a session if I attempt to set read deadlines on streams and cancel reads.

The scenario demonstrated is set up so that 50% of streams in a session time out and then attempt to "cancel". Eventually, all writers see the session level send window as exhausted and no reader can (or will) adjust it (even new ones after the fact).  All subsequent streams in the session then time out with no bytes received.

My theory is that some bytes on timed-out or read-cancelled streams are not accounted for / don't cause window adjustments -- perhaps in-flight bytes are accounted for on the write side, but not on the read side.  It is not possible from the perspective of a library-user to "drain" a read-cancelled stream afaict.

I'm not certain whether it is an issue with the implementation (like those bytes should be dropped, but still cause window adjustments), or whether this is more of a "don't-do-that" issue with the protocol.  Glad to provide more detail if it is helpful.

**Comment by marten-seemann** [comment]
Deadlines are a purely local operation that Go's `net.Conn` interface provides to make `Read` and `Write` calls return after the expiration of a deadline. Nothing is sent on the wire when you set a deadline.

This means that data received will sit in its buffer waiting to be read, consuming flow control credit. There's things you can do: Set the deadline to the future, or to `time.Time{}`, then you'll be able to read the data. Alternatively, you can call `CancelRead` on the stream, if you're no longer interested in reading the data.

**Comment by marten-seemann** [comment]
Can you try using an IETF QUIC version?
In IETF QUIC, `CancelRead` sends a STOP_SENDING frame:
https://github.com/lucas-clemente/quic-go/blob/93c7eb94ce4109373c0d3366b39daef66723136e/receive_stream.go#L197-L202
When receiving a STOP_SENDING frame, the peer will cancel writing
https://github.com/lucas-clemente/quic-go/blob/93c7eb94ce4109373c0d3366b39daef66723136e/send_stream.go#L291
and send a RST_STREAM frame, containing a final flow control offset for that stream
https://github.com/lucas-clemente/quic-go/blob/93c7eb94ce4109373c0d3366b39daef66723136e/send_stream.go#L253-L257

In gQUIC, things are more complicated, since the stream state machine was not designed to be general purpose, but for the HTTP/QUIC use case. After calling `CancelRead`, the RST_STREAM is only sent when you call `Close`. Receiving the RST_STREAM should make the peer respond with a RST_STREAM, which would then contain the final offset.

**Comment by forkner** [comment]
@marten-seemann Ah I see.  Sure, will do -- is the IETF version roughly as stable as the older gQUIC stuff at this point?

**Comment by ltucker** [comment]
@marten-seemann Ah I see. will do.  Is the IETF version roughly as stable as the older gQUIC stuff at this point?

**Comment by marten-seemann** [comment]
We're not maintaining any stable versions of IETF QUIC in the `master` branch, that's why `protocol.VersionTLS` is not an exported variable (although nothing can stop you from just copying the value for testing purposes... Just keep in mind that there's no compatibility guarantee between commits, i.e. things might break between commits if you build master with this version).

If you want a stable IETF QUIC version, you can vendor a release tag, e.g. https://github.com/lucas-clemente/quic-go/releases/tag/v0.10.0, which explicitly exposes a version number for IETF QUIC.

**Comment by ltucker** [comment]
@marten-seemann got it, thanks!

**Comment by ltucker** [comment]
@marten-seemann yup, works as expected in IETF quic.  I'll close this on the assumption that I'm just abusing GQUIC. :)
