### ISSUE TITLE
GQUIC: Unexpected STOP_WAITING frames should be ignored

### ISSUE THREAD

**Issue by dtikhonov** [lucas-clemente/quic-go#1604]
frame_parser.go contains this:

```
	case 0x6:
		if !v.UsesStopWaitingFrames() {
			err = errors.New("STOP_WAITING frames not supported by this QUIC version")
			break
```

This behavior is incompatible with Chromium, which ignores _STOP_WAITING_ frames in versions greater than Q043 or if NSTP option was set:

```
bool QuicConnection::OnStopWaitingFrame(const QuicStopWaitingFrame& frame) {
  DCHECK(connected_);

  // Since a stop waiting frame was received, this is not a connectivity probe.
  // A probe only contains a PING and full padding.
  UpdatePacketContent(NOT_PADDED_PING);

  if (no_stop_waiting_frames_) {
    return true;
  }
```

We noticed a connection failure in our LiteSpeed QUIC server with this error and it did not look familiar.

We will fix the LiteSpeed server code not to send _STOP_WAITING_ frames.  Currently, before the handshake is complete, the server sends _STOP_WAITING_ frames unconditionally.

**Comment by marten-seemann** [comment]
Those STOP_WAITINGs are super annoying. And it doesn’t make any sense to error on unknown frames, but then accept them anyway.
I’m happy to submit a fix as you suggested, if it makes Chrome happy...

**Comment by dtikhonov** [comment]
It's not the Chrome -- it's the quic-go client code that will be able to establish Q044 connections with LiteSpeed server.

**Comment by marten-seemann** [comment]
Sorry for the dumb question - we have integration tests using Google toy quic server, and it doesn’t happen there. Any idea why?

**Comment by dtikhonov** [comment]
My guess is that the Google toy server does the right thing and does not send _STOP_WAITING_ frames back during the handshake.

**Comment by marten-seemann** [comment]
So, I thought about this again. Since STOP_WAITING frames aren't supposed to be sent in Q044, then the correct behavior is to throw an error if we see an unsupported frame type. I don't know why Chrome is lenient here, but it doesn't seem to be the correct behavior.
As for LiteSpeed sending STOP_WAITINGs in Q044, this seems to be a bug in your code, doesn't it?

**Comment by marten-seemann** [comment]
Hi @dtikhonov, I disagree that the Chromium code is normative here. I guess the Google guys implemented it because they wanted to support the NSTP option (which quic-go doesn't, we're sending a Public Reset in that case), and ignoring STOP_WAITINGs is just the most straightforward way to do so. Anyway, thanks for reporting, it's good to cross-check our implementations!
