### ISSUE TITLE
vendored library qtls revision doesn't exist

### ISSUE THREAD

**Issue by Sean-Der** [lucas-clemente/quic-go#1781]
The vendor.json pins the library  `https://github.com/marten-seemann/qtls@061d608f3d22ea089c4c9039e1216eea999b9341` [here](https://github.com/lucas-clemente/quic-go/blob/master/vendor/vendor.json#L50)

This commit doesn't exist anymore so I am currently having some trouble pinning my gomodules to these revisions.

**Comment by marten-seemann** [comment]
That's exactly the reason why we commit the code in the *vendor* directory.

**Comment by Sean-Der** [comment]
The purpose of the vendor directory is so that you can keep the code working as upstream moves master along. That all makes sense to me.

In this case you have code vendored to a SHA1 that doesn't exist. It makes it really hard to audit the code/be sure what is actually going on. Since you have pinned to a SHA1 that doesn't exist you could make any changes to the code you wanted and no one would ever know, that seems like a nice way for someone to slip in a backdoor.

**Comment by marten-seemann** [comment]
The code corresponding to the hash in the vendor directory, so I don’t see how this could be used to introduce a backdoor. When you clone the repository, you get all the code including dependencies.

**Comment by Sean-Der** [comment]
Does that hash verify anything more then the validity of the contents of the directory? I am not worried about someone making changes after the initial commit of vendoring qtls.

If the SHA1 no longer exists in the qtls repo how can I confirm what you actually copied from the qtls repository? You could have copied and then made a minor change and I would never know. If that SHA1 exists and all the files match I can be sure you actually vendored what you said.

**Comment by marten-seemann** [comment]
You're right, vendoring only copies the files, not the git history. So the hash is basically worthless.

**Comment by trivigy** [comment]
@marten-seemann the real problem here is that this completely contradicts to how go modules work. Go modules do not use vendor folder when this project is imported as a dependency. So go modules tries to grab stuff from the actual repo which no longer has the right hashes. And since go modules is the future of golang I would raise that it is a real issue. I would recommend to not delete any commits from public dependency libraries going forward.

This is also a definite compatibility problem for #1547 #1548 #1620 because now that old commits are missing from github.com/marten-seemann/qtls, anyone who is dependent on older version of quic will suffer from go modules spitting issues of not being able to find the right dependencies. Really not sure even how to help here.
