### ISSUE TITLE
go get quic-go build failure

### ISSUE THREAD

**Issue by veily** [lucas-clemente/quic-go#1797]
```
go get github.com/lucas-clemente/quic-go@v0.10.1
# github.com/lucas-clemente/quic-go/internal/crypto
../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.10.1/internal/crypto/key_derivation.go:46:37: cs.KeyLen undefined (type mint.CipherSuiteParams has no field or method KeyLen)
```

**Comment by marten-seemann** [comment]
We don't support go mod, especially not for older versions.

**Comment by veily** [comment]
mint upgraded mint.CipherSuiteParams struct  remove KeyLen and IvLen.

**Comment by marten-seemann** [comment]
That's why we're using vendoring.

**Comment by grebnetiew** [comment]
I have no idea what that means, to be honest. How does one use your vendored project within a project managed by go mod?

I understand I will have to learn about shaving this yak to be able to use this package, but it would help a lot if the Readme would briefly summarize the proper installation procedure. Alternatively, is there a list somewhere of the specific versions of mint etc. on which you depend, so that users of go mod can just add those to the dependency file?

**Comment by marten-seemann** [comment]
Thanks for the explanation, @grebnetiew. This is really helpful.
I'll add go mod support soon, although this will only apply to new releases, not to old ones. 
To be honest, I don't know what the right procedure here would be if I wanted to add go mod for old releases. Delete the tag, add go mod, and re-tag that? Doing that for every single release I made in the past doesn't sound very practical (and it would mess with people's git histories).
