### ISSUE TITLE
What is likely cause of "Too many outstanding received ACK ranges" error?

### ISSUE THREAD

**Issue by mathiasxx** [lucas-clemente/quic-go#2010]
I got this error on v0.11.2 after leaving up a quic connection for about 70hours.  Not much was going on over the connection.  Both hosts sitting in AWS EC2.   Could this error indicate a transient network connectivity issue, or is it more likely to be misconfiguration?  Is the appropriate remediation to just open a new stream?

 I'm attempting to use quic for  long running connections in a VPN-style setup. I'm bringing up a single stream on a session at the start and just treating it like a socket.  I know this is sub-optimal, and I will switch to using multiple shorter lived streams.  But this approach allowed me to simply drop quic in where TCP used to be, and I figured that this setup would be ok for initial testing.  Am I already running into trouble by using this approach I wonder?

Thanks for any tips!

**Comment by marten-seemann** [comment]
Hi @mathiasxx, the `errTooManyOutstandingReceivedAckRanges` exists to [protect](https://github.com/lucas-clemente/quic-go/blob/7a294f6a78fbafa6670874f6a01cd225dc139ec3/internal/ackhandler/received_packet_history.go#L29-L32) us from a DoS attack by a malicious peer. It occurs when we receive too many gaps in received packet number. The extreme case would be if we receive every second packet, e.g. receiving packet 1, 3, 5, 7, ... and missing every packet in between, [more than 1000 times](https://github.com/lucas-clemente/quic-go/blob/7a294f6a78fbafa6670874f6a01cd225dc139ec3/internal/protocol/params.go#L76-L77).

The reasoning behind this is that in order to generate acknowledgements, we need to keep track of **ranges** of packets that were received (for example, if we receive packets 1, 2 and 3, the range would be 1-3), and a malicious peer could force us to save an unbounded number of ranges. In practice, this **should** never occur, since we clean up old received ranges from time to time. It looks like this is not working properly.

Thinking about it, I'm not sure if this error makes sense at all. Since all QUIC frames are idempotent (i.e. processing a frame a second time doesn't change any connection state), we can just throw out old ranges if we determine that we're keeping track of too many of them. This will appear as packet loss for the sending peer, and we might receive a retransmission for a packet that we actually already received. However, since this is a defense against a malicious peer, this shouldn't matter in practice, as long as we commit to store a large enough number of ranges.

**Comment by mathiasxx** [comment]
@marten-seemann thanks for the explanation.
