### ISSUE TITLE
VarInt panic

### ISSUE THREAD

**Issue by AudriusButkevicius** [lucas-clemente/quic-go#2059]
Seems to have been caught by syncthing, just being a good citizen and reporting: https://sentry.syncthing.net/share/issue/530c98b47dd24b9eb1f80070c59728f0/

**Comment by AudriusButkevicius** [comment]
Don't dig too deep, if this could be bad hardware, then it probably is.

**Comment by marten-seemann** [comment]
Thanks for reporting this @AudriusButkevicius!
Do you happen to know the guys at Sentry? It would be really benefitial f they reported issues like these to us directly. Otherwise problems like this one might go unnoticed for a long time...

**Comment by AudriusButkevicius** [comment]
Sentry is just a error aggregation tool that we use, not much todo with the crash itself.

**Comment by marten-seemann** [comment]
I see. Do you have any more information about the crash?
I don't believe it's bad hardware, there must be a better explanation. And I want to understand what's going on here, and fix the real problem, instead of implementing the obvious workaround.

Here's how far I got so far with my investigation:
* The problem seems to be that we're trying to encode the value `0xffffffffffffd763`. This value is just 10396 smaller than MaxUint64, so I'm assuming that we're dealing with a uint64-underflow here, and we're trying to encode -10396.
* The panic occurs in this line https://github.com/lucas-clemente/quic-go/blob/4355e1a7e961ba3b6005cb035ae17732181c9508/internal/wire/ack_frame.go#L144
 Unfortunately this line contains two calls to `utils.VarIntLen()`, but I think we can exclude the possibility that the largest acked packet is larger than 1<<62 (the biggest encodable varint value). That means that it's the `DelayTime` is negative.
* The `DelayTime` is set in https://github.com/lucas-clemente/quic-go/blob/4355e1a7e961ba3b6005cb035ae17732181c9508/internal/ackhandler/received_packet_tracker.go#L169-L181, i.e. it's the difference between a `time.Now()` call done right in this function, and the time the of the largest observed packet (which is determined by a `time.Now()` call earlier). It looks like that time difference is negative here.

This looks suspiciously like the bug [CloudFlare encountered](https://blog.cloudflare.com/how-and-why-the-leap-second-affected-cloudflare-dns/) a few years ago. The problem is, this bug was solved with the introduction of a monotonic clock in Go 1.9 (and it's not possible to build quic-go with Go 1.8).

**Comment by AudriusButkevicius** [comment]
From what you've presented above it seems to me there is no likely way this could happen under normal conditions (unless largestObservedReceivedTime is coming from a remote side, then clocks being out of sync totally possible), in which case I strongly think it's just bad hardware. 

People run syncthing on all sorts of raspberry Pi's and other grim unreliable hardware.

This also might be a problem with rpi being late to sync with ntp, namely it does an ntp sync after syncthing has started which potentially makes the time move back.

**Comment by marten-seemann** [comment]
> From what you've presented above it seems to me there is no likely way this could happen under normal conditions (unless largestObservedReceivedTime is coming from a remote side, then clocks being out of sync totally possible), in which case I strongly think it's just bad hardware.

We record the time when we receive the packet, so this is not an issue of clock synchronization. I think it’s highly unlikely that this is a hardware issue. These timestamps are kept in memory for a very short time, so it’s not very likely that a corruption occurs there (and the corruption is that close to 0).

> This also might be a problem with rpi being late to sync with ntp, namely it does an ntp sync after syncthing has started which potentially makes the time move back.

If I understand correctly, this is analogous to the issue that CloudFlare encountered, and it should have been solved by the introduction of monotonic clocks in Go.

**Comment by AudriusButkevicius** [comment]
Just checked, this issue happened on solaris amd64 with go 1.12.7.

There is only a single report of this type, so perhaps it's still bad hardware, or perhaps monotonic clocks don't work on solaris.

**Comment by raulk** [comment]
encodeAckDelay deals with nanosecond resolution, but some OSes offer maximum millisecond resolution. This is the case of Windows, and I wonder if something similar could be happening with Solaris. We had a similarl gotcha elsewhere recently.

https://github.com/lucas-clemente/quic-go/blob/4355e1a7e961ba3b6005cb035ae17732181c9508/internal/wire/ack_frame.go#L225

**Comment by marten-seemann** [comment]
@raulk If the underlying clock is monotonic, resolution shouldn't matter, should it? A low-resolution clock would just lead to a difference that's 0 for intervals shorter than the resolution.

@kubuxu says that monotonic clock support is added in Solaris 12 (the current version is 11.4). Haven't been able to find a source for that yet, but that would explain the issue here.

**Comment by raulk** [comment]
@marten-seemann yeah, you're right.

I do see different time units being used, and I wonder if the underlying cause could be a programmatic or wire-level loss in precision. `encodeAckDelay` deals with nanoseconds, but `DelayTime` is initialised with microsecond resolution when read from a frame.

**Comment by marten-seemann** [comment]
You're right, the encoding causes a loss in precision here. Deliberately, in order to save bytes on the wire. The ACK delay is used to correct the RTT for sender-side delays when sending acknowledgements, so if you're dealing with typical RTTs in the order of ~10ms, a resolution of 8mus should be good enough.

**Comment by Kubuxu** [comment]
To correct my statement, Solaris supports monotonic time since a while but Golang doesn't use it (why, I have no idea).

In golang monotonic time `get` functions are called `nanotime`, as you can see in case of solaris it uses `CLOCK_REALTIME`, not `CLOCK_MONOTONIC`: https://github.com/golang/go/blob/master/src/runtime/sys_solaris_amd64.s#L32-L50

**Comment by marten-seemann** [comment]
Thanks @Kubuxu, this is really helpful, and makes me more confident that #2061 is actually a fix, rather than a workaround.

**Comment by AudriusButkevicius** [comment]
I think something should be open in the go tracker about this, or do you think no?

**Comment by Kubuxu** [comment]
I think it is worth opening something.

**Comment by AudriusButkevicius** [comment]
Raised https://github.com/golang/go/issues/33674
