### ISSUE TITLE
Checksum mismatch on v0.12.0 with go1.13

### ISSUE THREAD

**Issue by imsodin** [lucas-clemente/quic-go#2129]
When quic-go is not cached go 1.13 reports a checksum error when building/installing.

Steps to reproduce:

1. Start in a clean environment (or remove `$GOPATH/pkg/mod/.../quic-go@v0.12.0`) and make sure that the module you are currently in (if applicable) does not contain an entry for quic-go in its go.sum file.
2. Run `go get github.com/lucas-clemente/quic-go`

Result:
```
go: extracting github.com/lucas-clemente/quic-go v0.12.0
verifying github.com/lucas-clemente/quic-go@v0.12.0: checksum mismatch
        downloaded: h1:dYHUyB50gEQlK3KqytmNySzuyzAcaQ3iuI2ZReAfVrE=
        sum.golang.org: h1:TRbvZ6F++sofeGbh+Z2IIyIOhl8KyGnYuA06g2yrHdI=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by marten-seemann** [comment]
I can't reproduce this.
I first ran `go clean -cache -modcache`, which empties `$GOPATH/pkg/mod/`. I then `go get`ted quic-go from a directory outside the GOPATH, and everything worked out fine.

**Comment by imsodin** [comment]
Indeed I can't either anymore, I must have mixed something up - sorry about the noise and thanks for checking.

The problem came up because in Syncthing's checked in go.sum we have `dYHUyB50gEQlK3KqytmNySzuyzAcaQ3iuI2ZReAfVrE=` and that worked on all the dev's and CI's build due to caching. So I am curious as to how that happened. The only thing that came to mind was that the v0.12.0 tag moved. Is that possible?

**Comment by artemnesterenko** [comment]
Facing the same issue

**Comment by zserge** [comment]
Actually, I would like to reopen this, since things are messed up.
I tried to download the module without any caching proxies.

```
GOPATH=/tmp/_gopath GOPROXY=direct GOSUMDB=off go mod download github.com/lucas-clemente/quic-go@v0.12.0
```
This results in:
```
cat /tmp/_gopath/pkg/mod/cache/download/github.com/lucas-clemente/quic-go/@v/v0.12.0.info
{"Version":"v0.12.0","Time":"2019-08-05T01:25:16Z"}
```

Now, if I go to the official golang proxy (which is turned on by default since Go 1.13), I see:

```
// https://proxy.golang.org/github.com/lucas-clemente/quic-go/@v/v0.12.0.info
{"Version":"v0.12.0","Time":"2019-08-05T01:00:23Z"}
```

Notice the different timestamp. This makes me think the tag was moved 25 minutes after the initial release. In either way, the tag v0.12.0 is broken and Golang proxy has no way to invalidate modules, which means it has forever stored the invalid commit reference (25 minutes earlier than the current tag), so any attempts to validate the checksum against it will fail.

This affects everyone who uses their own near proxies in CI pipelines (that cached the module at least 25 minutes later it was first released) or uses no proxy at all.

Please, put another untainted tag for this release.
