### ISSUE TITLE
github.com\lucas-clemente\quic-go@v0.12.0\internal\handshake\crypto_setup.go:501:72: undefined: qtls.CipherSuite

### ISSUE THREAD

**Issue by dingjianfeng** [lucas-clemente/quic-go#2151]
When I use the command :go get -u -v github.com/micro/go-micro to install go-micro, the terminal display github.com\lucas-clemente\quic-go@v0.12.0\internal\handshake\crypto_setup.go:501:72: undefined: qtls.CipherSuite.

**Comment by oxlay** [comment]
@marten-seemann encountering the same issue here, could you please give some context on how to solve it?

**Comment by AllenKaplan** [comment]
Hi there, I see this issue is closed, but I am having this occur and I have not found a solution. 

I have used `go clean -modcache` and the error appears after attempting to download the go-micro module of which quic-go is a dependancy.

Help would be greatly appreciated, thanks you! 

Reference: https://github.com/micro/go-micro/issues/870
