### ISSUE TITLE
Heavy dependencies are causing build limitations

### ISSUE THREAD

**Issue by mholt** [lucas-clemente/quic-go#2219]
Some quic-go dependencies do not build on platforms that we'd like to continue to support:

- https://github.com/hpcloud/tail/issues/161
- https://github.com/onsi/ginkgo/issues/622

Despite [an open PR](https://github.com/hpcloud/tail/pull/162) to fix hpcloud, the repo appears to be abandoned.

Ginkgo is a testing library; it would be nice if it was only compiled for tests.

Because of these errors, we can no longer distribute Caddy for:

- Dragonfly
- Illumos
- NACL
- Plan 9
- Solaris

Would you be willing to somehow drop these dependencies or use patched forks?

**Comment by marten-seemann** [comment]
Is there any way to make Go distinguish between build and test dependencies?

**Comment by mholt** [comment]
Yeah... I mean, it already does: anything in `_test.go` files will only be compiled for tests.

But ginkgo is used in normal, non-test go files such as https://github.com/lucas-clemente/quic-go/blob/9e6bff0b987279f38c6d9e7f055d95a9c8da832f/integrationtests/tools/testserver/server.go#L16.

**Comment by marten-seemann** [comment]
Does that mean that if we manage to move the test server to `_test.go` files, everything would work fine?

**Comment by mholt** [comment]
I think so -- I will try that and let you know.

**Comment by marten-seemann** [comment]
I don't really know what is pulling in `hpcloud`. It's not in the `go.mod` file anyway.
`go mod why` doesn't work on it (because of that?).

It looks like that Gomega (Ginkgo's matcher library) pulls it in though: https://github.com/onsi/gomega/blob/master/go.mod.

**Comment by Mohammed90** [comment]
It's used in ginko here:
https://github.com/onsi/ginkgo/blob/master/internal/remote/output_interceptor_unix.go

It seems like it's being used as a buffer to intercept the output for inspection. Wouldn't stdlib's [pipe](https://golang.org/pkg/io/#Pipe) be useful here?

**Comment by marten-seemann** [comment]
@Mohammed90 Can you please copy this comment over to the Ginkgo repository?

**Comment by nmiyake** [comment]
Chiming in since I've arrived at a similar place while trying to clean up module import dependencies.

Will note that it looks like `quic-go/integrationtests/tools/testserver/server.go` is a non-test Go file, but it's meant to be part of integration tests. Making this a test Go file should make a normal build succeed, but the test dependencies will still be part of the module dependency graph. The downside of making the test server a `_test` file will be that other files in integration tests that are not in the same package will not be able to import it.

Would like to make a possible suggestion that I've used for some of my projects -- you could consider making `quic-go/integrationtests` its own module. Process is roughly:

* Create module in `quic-go/integrationtests`: `go mod init github.com/lucas-clemente/quic-go/integrationtests`
* In its `go.mod` file, add the directive `replace github.com/palantir/quic-go => ../`
* Update your CI/CD logic to build/run everything in the integration tests directory

The advantage of this approach is that, by making the integration tests a separate module, dependencies pulled in only by the integration tests are no longer pulled in as part of the core module. The integration tests will still run against the latest code due to its replace directive.

The disadvantages are the extra maintenance overhead of having multiple modules in the repository, and that consumers of the primary module will no longer get the integration tests (they will not be able to run them with `go test all`).

Happy to open a PR for this if you're interested to see what this approach would look like for this repo. Totally understand if you're not open to this approach (I've only done this on a case-by-case basis for my own repositories because of these drawbacks), but wanted to offer it as a possibility since this approach has been useful for me to isolate integration test dependencies when they've caused issues.

**Comment by marten-seemann** [comment]
Thank you @nmiyake, that's an interesting idea. Hadn't thought about this before.

In this case, I think we're ok with not doing it though. I figured out that we don't really need the `testserver` package any more, and I moved the code in that package into the other places where it was needed in #2246. This still leaves Ginkgo in the dependency tree, but at least it shouldn't be needed any more to build the (non-test) code. So I believe this will fix @mholt's problem.

**Comment by mholt** [comment]
One other possibility would be to move those tests into a separate repo entirely. (We'll probably do something like this for Caddy 2.)

**Comment by nmiyake** [comment]
Moving tests into a separate repo is definitely a possibility as well, but one downside/wrinkle there is that the tests will typically only run against tagged/completed builds of the repo that it's testing. This may be fine for some scenarios, but doesn't work if you want to use integration tests to verify PRs/changes on the primary repo. The submodule case does allow this, since by using the local replace directive the integration tests will run against the local code -- this allows the integration tests to still verify changes on the primary repo, while also isolating them as a separate module.

**Comment by marten-seemann** [comment]
@mholt I think #2246 and #2250 will solve the build issue that you reported. Even if we were to completely remove the integration tests from this repository, we'd still pull in Ginkgo for the unit tests, so I don't think this would help in this case. Also, I really want the integration tests to run on every commit and PR.

**Comment by mholt** [comment]
That sounds great, however you choose to fix this is fine with me. Thank you for working on this!

**Comment by marten-seemann** [comment]
Fixed by #2246 and #2250.
