### ISSUE TITLE
Extract the ErrorCode

### ISSUE THREAD

**Issue by r0l1** [lucas-clemente/quic-go#2441]
I am unable to extract the error code, because the QuicError is hidden within the internal package. Are there any plans to allow access to user defined application errors?

**Comment by marten-seemann** [comment]
Can you do an interface assertion on the error code returned?

**Comment by r0l1** [comment]
The QuicError is a struct type, not an interface. That's why it is not possible.

```go
type QuicError struct {
    ErrorCode    ErrorCode
    FrameType    uint64 // only valid if this not an application error
    ErrorMessage string
    // contains filtered or unexported fields
}
```

I would expect a public library interface as:

```go
type QuicErrorCode interface {
    ErrorCode()    ErrorCode
}
```

and the internal QuicError must also be transformed to an interface
```go
type QuicError struct {
    ErrorCode()    ErrorCode
    FrameType()    uint64
    ErrorMessage() string
}
```

**Comment by marten-seemann** [comment]
Thanks for the proposal. Some thoughts:

1. Frame type is probably not very interesting to expose.
2. There needs to be a way to expose if the error is an application error or a QUIC error. For QUIC errors we probably don't even need to offer an `ErrorCode()` function.
3. How would you distinguish between a connection that the peer closed vs. a connection that we closed ourselves?
4. Not every error has an error code though, most notably, stateless resets don't. Any suggestion how that could be handled?

**Comment by marten-seemann** [comment]
Related: #2669. Maybe we should do something along the lines of the `logging.CloseReason` introduced there for the error that we return to the application.

**Comment by develerik** [comment]
Any update on this?

**Comment by apmattil** [comment]
just some ideas:

1. Frame type is probably not very interesting to expose.
??

2. There needs to be a way to expose if the error is an application error or a QUIC error. For QUIC errors we probably don't even need to offer an ErrorCode() function.
- wrap internal errors ?

3. How would you distinguish between a connection that the peer closed vs. a connection that we closed ourselves?
- use function e.g PeerReset(), just like we have Timeout()
- const errors ?

4. Not every error has an error code though, most notably, stateless resets don't. Any suggestion how that could be handled?
- do as in case 3 ?

IMHO: 
- we need some failure codes or functions to indicate what went wrong, e.g if we get crypto/cert error there is no point to create a new stream for that session.
- indication is the problem stream or session one.
- if you just make browser and on every failure assume user will retry later, current implementation is suffient. But when user has some streaming app you get into troubles.

**Comment by VinozzZ** [comment]
Is there anything that I can do to help pushing this effort forward? We are also trying to ignore the success closing error `0x0`

**Comment by mgranderath** [comment]
This is definitely not a good solution and should only be used if really needed but I am currently extracting the `ErrorCode` using reflection. I'm using this for a scientific project and not in an production environment so this is currently fine for me. 

```golang
// where err is the quic error
errorCode := reflect.ValueOf(err).Elem().FieldByName("ErrorCode").Uint()
```

This is a shortened version and you have to make sure that `err` is actually of type `qerr.QuicError`

**Comment by thepaul** [comment]
It might be sufficient just to move (or type-alias) the `quic-go/internal/qerr.QuicError` type out of `internal`. If we could do

    var quicErr *qerr.QuicError
    if errors.As(err, &quicErr) {
        if quicErr.IsApplicationError() {
            applicationError = quicErr.ErrorCode
        }
    }

in our own code, that would be good enough for current needs, as far as I can tell, and no one would need to use the `reflect` package shenanigans. :grin: Also, it would be nicely backward-compatible, even for uses of said shenanigans.

**Comment by marten-seemann** [comment]
Summarizing the status, and looping in @mvdan: We're trying to achieve here is to make the error returned from a QUIC connection meaningful.

There are a lot of reasons why QUIC connections might get closed:
1. One of the many transport errors (usually protocol violations) might occur. Either peer can trigger such an error, so there should be a way to tell which side errored.
2. An error code from the space of application-level error codes. Again, either peer can trigger this error.
3. A timeout occurred. Note that we distinguish between a few different kind of timeouts, most notably idle timeouts (before and after the handshake) as well as handshake timeouts (if the entire cryptographic handshake took too long).
4. We might receive a stateless reset.
5. We might be unable to dial a server because there's no overlap between our and their versions.
6. The context we used for dialing is canceled.

We definitely want to implement `net.Error` (we already do that), since this allows applications to re-dial in the case of temporary errors.
I'm wondering if we should just export a `quic.TransportError`, `quic.ApplicationError`, `quic.TimeoutError`, `quic.StatelessResetError` and a `quic.VersionNegotiationError`. For context cancelations, we would just return the `ctx.Err()`.
The structs would contain all the fields that might be interesting for that kind of error, for example
```go
type quic.TransportError struct {
    Remote bool // who sent the error
    ErrorCode uint64
    ErrorMessage string
}
```

An application interested in the details of the error could then implement a `switch` statement doing `errors.As` assertions to check for the specifics of the error. For applications that are not interested in that level of detail, every one of these types would have to implement `net.Error` (with the exception of the context errors probably, as they're often compared with `err == context.Canceled`).

**Comment by marten-seemann** [comment]
Related: The `logging.CloseReason` feels very messy: https://github.com/lucas-clemente/quic-go/blob/3138a45fded18b7c15c12424ea662127b4b80c9f/logging/close_reason.go#L9-L17

Maybe we can do something analogous to whatever we decide for the error we return?

**Comment by apmattil** [comment]
I assume 1.st point in the list includes tls errors ?
Also dial can fail due route not found, but that we can dig out from net.Error

**Comment by mvdan** [comment]
Exporting error types and allowing the use of `errors.As` seems sane to me. I'm not sure if you are hesitant about the extra API surface, or about whether there might be a better way to expose this in the API. I think what you proposed is the standard.
