### ISSUE TITLE
Make tests pass with the race detector enabled

### ISSUE THREAD

**Issue by Stebalien** [lucas-clemente/quic-go#2520]
Running the tests with the race detector enabled reveals several races but it's unclear which ones are just test issues and which ones are issues with the actual code.

**Comment by marten-seemann** [comment]
This only applies to the `quic` package. Most (and with #2385 all) other packages can be run with race detector.

Most importantly, we run the integration tests with race detector on CI: https://github.com/lucas-clemente/quic-go/blob/c0b6d4e141d6dca43023a8c9ae0f437bb943f182/.circleci/config.yml#L45-L47

Running the `quic` tests with race detector would be super nice, but unfortunately a lot of work, since we didn't pay attention to make the tests race-free back when we started the project a few years ago...

**Comment by Stebalien** [comment]
I'd at least try running them with the race detector and see what it spits out. I saw several issues that looked real.
