### ISSUE TITLE
High CPU usage from timers

### ISSUE THREAD

**Issue by Stebalien** [lucas-clemente/quic-go#2601]
I'm seeing a significant amount of CPU usage(20%)  from timer usage on [hydra](https://github.com/libp2p/hydra-booster/) after enabling QUIC.

Pprof profiles: [profile-hydra-2020-06-12T07:36:35-0700.tar.gz](https://github.com/lucas-clemente/quic-go/files/4771511/profile-hydra-2020-06-12T07.36.35-0700.tar.gz)

Unfortunately, the profile doesn't tell us where this is coming from. However, I'm _guessing_ it's coming from resetting the session timer for every packet. Instead of resetting it on every packet, we should ideally extend it only when the deadline changes significantly (e.g., doubles from the previous deadline). For example, in yamux, we extend the [write deadline](https://github.com/libp2p/go-yamux/blob/7bf6d4a1d537d0319dddd29d3eb180851c83b5c5/session.go#L415-L423) whenever it elapses half way. This leads to some fuzzy guarantees, but that's usually good enough anyways.

**Comment by marten-seemann** [comment]
This will be tricky. QUIC relies on accurate and millisecond (and in some cases sub-millisecond) timers, most importantly for:

- when sending: for pacing packets. Pacing is very important to avoid sending out bursts of packets that would overload the network. When using pacing, one congestion window worth of packets is sent out evenly spaced out over one RTT. We already do have an optimization here that prevents the use of overly short timers (by sending out a very small burst): https://github.com/lucas-clemente/quic-go/blob/5f9fc462ea3d7659b8c0a48f8a1805ed1107d0c5/internal/protocol/params.go#L133-L136
- when receiving: for generating acknowledgements. We need to generate frequent and timely acknowledgements to drive the peer's congestion controller and to avoid spurious retransmissions of packets. When receiving a constant stream of packets, we don't acknowledge every packet though, but only every other packet. However, we are required to send an acknowledgement within the _max_ack_delay_ (25ms) after receipt of a packet, so we need to set a timer for this.

As a way forward here, I'll build some counting into the timer to get a histogram of timer duration we use. If it turns out that most of the time the duration we set is long (> 1s or so), we might be able the yamux optimization here.

**Comment by Stebalien** [comment]
Would it be possible to share a single across a single QUIC session?

**Comment by marten-seemann** [comment]
@Stebalien Now that IPFS v0.7.0rc1 has been out for a few days, can you please check if this issue has been resolved? The new pacing algorithm released with quic-go v0.18 should give us significant improvements here, but I'd like to see if that's how it actually plays out in production before closing this issue.

**Comment by Stebalien** [comment]
I've done a bit of testing on one of the bootstrappers, and haven't noticed any issues. But someone'll need to pull some cpu profiles from hydra to make sure.

**Comment by marten-seemann** [comment]
I assume this problem has been solved. Closing for now, feel free to reopen.
