### ISSUE TITLE
Re-evaluate dependencie

### ISSUE THREAD

**Issue by AudriusButkevicius** [lucas-clemente/quic-go#2618]
It seems this library transitively pulls in `database/sql/driver` via `gojay`.
Given it's a transport library, I'd expect it to be a lot leaner.

Is the performance gain of gojay really worth the binary bloat?

**Comment by marten-seemann** [comment]
Unfortuantely, `encoding/json` is horribly slow due to its heavy use of reflections, so in order to have logging with a minimal performance impact, there's no way around a third-party JSON library.

That being said, I've been nagging @rmarx (the author of the qlog spec and creator of the awesome qvis visualization tools) for quite a while to move to a more efficient encoding format (see https://github.com/quiclog/internet-drafts/issues/30). However, even once this issue is resolved, this would likely just allow us to *replace* gojay with an encoding library for whichever format qlog will end up with.
