### ISSUE TITLE
fix dequeueing of immediate RTO retransmissions

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#264]
Sometimes, we're dequeueing a retransmission for a packet while we're just sending it.

```
-> Sending packet 0xa (26 bytes)
	-> &frames.AckFrameLegacy{LargestObserved:0x6, Entropy:0x2e, NackRanges:[]frames.NackRange(nil), Truncated:false, DelayTime:23441, PacketReceivedTime:time.Time{sec:63606147342, nsec:370955478, loc:(*time.Location)(0x788c80)}}
	Dequeueing retransmission for packet 0xa
```

Happens with the old an the new AckHandler.

**Comment by lucas-clemente** [comment]
Does this still happen with the new ackhandler?

**Comment by marten-seemann** [comment]
Yes 👎

**Comment by lucas-clemente** [comment]
It seems this only happens when Chrome is launched with an URL from the shell. With some additional logging, it looks like it stops sending packets for a short while (>200ms), and therefore triggers an RTO. This does not happen when a normal download is started while the browser is running.

There's nothing we can or need to do.
