### ISSUE TITLE
Possible data race: A field in a structure is sometimes protected by Mutex, but sometimes unprotected.

### ISSUE THREAD

**Issue by BurtonQin** [lucas-clemente/quic-go#2717]
A field in a structure is sometimes protected by Mutex, but sometimes unprotected.
This may lead to data race.
`s.currentFrame` is not protected by `s.mutex` on L168 in `receiveStream.readImpl()`. But for all the other places, it is protected by `s.mutex`.
https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/receive_stream.go#L166-L168
 `c.destConnID` and `c.version` are not protected by c.mutex on L245 in `client.dial()`. But for all the other places, it is protected by c.mutex.
https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/client.go#L244-L245

I found these inconsistencies through static analysis. Not sure if data race can actually happen in production.

I think `s.currentFrame` is more likely to have issues. All the calls to `s.dequeueNextFrame()` (which writes to `s.currentFrame`) are in the critical section, but since there is one read to `s.currentFrame` not in the critical section, I think it may have data race.

**Comment by egonelbre** [comment]
@BurtonQin is the static analysis tool public you were using?

**Comment by marten-seemann** [comment]
> s.currentFrame is not protected by s.mutex on L168 in receiveStream.readImpl(). But for all the other places, it is protected by s.mutex.

There's no requirement to be consistent with accessing a variable only with or without a mutex. In fact, that would be very bad for performance. Once you locked a mutex (maybe because you need it locked to access another variable), you wouldn't unlock it just to access it.
Access to a variable has to be protected by a mutex if and only if multiple Go routines make use of that variable concurrently.

This is not the case with `currentFrame` in the `receiveStream`. This variable is set by `dequeueNextFrame`: https://github.com/lucas-clemente/quic-go/blob/27448c1fa520eddeda78cde02566d8b219963ba7/receive_stream.go#L186-L195

Now `dequeueNextFrame` is only ever called from `readImpl`. Furthermore, the only function that's accessing `currentFrame` is in fact `readImpl`, i.e. this variable is only ever accessed from a single Go routine, and therefore doesn't need to be protected by a mutex.

**Comment by marten-seemann** [comment]
I think you're right about the mutex in the `client`. Looks like this is not need (any longer), after we moved version negotiation to the session.
