### ISSUE TITLE
"Too many gaps in received StreamFrame data" in upload test

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#298]
```
• Failure [3.884 seconds]
Chrome tests with quic version 33 [It] uploads a large file 
/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/chrome_test.go:186
  Expected error:
      <*errors.errorString | 0xc8257f3a30>: {
          s: "multipart: Part Read: InternalError: Too many gaps in received StreamFrame data",
      }
      multipart: Part Read: InternalError: Too many gaps in received StreamFrame data
  not to have occurred
  /home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/integrationtests_suite_test.go:120
  Full Stack Trace
  	/home/travis/gopath/src/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x32d
  github.com/onsi/gomega/internal/assertion.(*Assertion).ToNot(0xc825880500, 0x7f41369c4160, 0xc4e8d8, 0x0, 0x0, 0x0, 0xc825880500)
  	/home/travis/gopath/src/github.com/onsi/gomega/internal/assertion/assertion.go:39 +0x92
  github.com/lucas-clemente/quic-go/integrationtests.setupHTTPHandlers.func5(0x7f413697cc78, 0xc8296e9e00, 0xc827922000)
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/integrationtests/integrationtests_suite_test.go:120 +0x156
  net/http.HandlerFunc.ServeHTTP(0xa5f350, 0x7f413697cc78, 0xc8296e9e00, 0xc827922000)
  	/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1618 +0x3a
  net/http.(*ServeMux).ServeHTTP(0xc820014ed0, 0x7f413697cc78, 0xc8296e9e00, 0xc827922000)
  	/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1910 +0x17d
  github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1.1(0xc829069f4f, 0x7f413697cc50, 0xc820014ed0, 0xc8296e9e00, 0xc827922000)
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/h2quic/server.go:182 +0x91
  github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0xc8201be8a0, 0xc8296e9e00, 0xc827922000, 0x7f413697b860, 0xc8270c2000)
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/h2quic/server.go:183 +0x95
  created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
  	/home/travis/gopath/src/github.com/lucas-clemente/quic-go/h2quic/server.go:196 +0xab5
```

**Comment by marten-seemann** [comment]
I addad an upload-handler to the demo server in c2af049. This should make debugging a lot easier.

**Comment by marten-seemann** [comment]
I thought about increasing the `errTooManyGapsInReceivedStreamData`, which currently has a value of 50. To reasonable account for the higher congestion parameters now used by the current Beta of Chrome, we'd have to increase this value to 500 or 1000.

The problem is that this would make us vulnerable to a DoS attack.
We're saving all gaps in a linked list, and a malicious client can force us to iterate through each element in this list. Since a `StreamFrame` header is about 10 bytes of data, that comes down to 5 iterations per byte of data sent. Because list iterations behave as `O(N)`, increasing the limit by one order of magnitude would also increase the number of operations by the same factor.

The problem here is (of course), that a linked list is by no means the best data structure here. It would be more efficient to store the gaps in a data structure that allows for binary searches, which would reduce the lookup time for an incoming `StreamFrame` to `O(log N)`. Since under normal conditions, gaps are created and closed all the time, the best choice would probably be some flavor of a balanced tree.

What I'd suggest now is the following:
1. We increase the limit in order to ensure compatibility with the current pre-releases of Chrome.
2. We create a new issue to implement a better data structure as described above.
