### ISSUE TITLE
Improve performance under packet loss

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#302]
We currently are a lot worse than TCP or Google's implementation under packet loss. We should debug this and improve.

Some interesting resources:
- https://quic.eimji.io/quicvstcp
- https://tools.ietf.org/html/draft-tsvwg-quic-loss-recovery-01

**Comment by jared2501** [comment]
Hey @marten-seemann --

I'm running quic-go on an LTE connection I'm seeing situations where the number of UDP packets will drop sharply and then stay at a low level for a period of time (maybe a minute or two) before rising. Is this expected right now on lossy connections? It appears that this might be something you're currently working on improving in quic-go - is that correct?

Here's a datadog dashboard showing such an event where the outgoing rate of UDP packets drop sharply, despite there being available application data (i.e. the "dropped frames" dashboard shows that application frames were pending but dropped since the connection did not have enough bandwidth): 

![image](https://user-images.githubusercontent.com/2866738/38176854-6112209c-35ab-11e8-8808-96c39a5f6241.png)

**Comment by jared2501** [comment]
So after a bit of logging I noticed that I was getting an excessive amount of RTO timeouts in a row during these events, despite the congestion window remaining at the minumum. I didn't manage to get a read out of the RTO timeout during one of these events, but since I'm operating on LTE with an RTT of ~150ms-250ms I changed the minimum RTO timeout to 300ms and haven't seen any further issues.

**Comment by jared2501** [comment]
Looking forward to some BBR! :)

**Comment by marten-seemann** [comment]
This makes sense, since we don't have spurious RTO detection yet.

**Comment by marten-seemann** [comment]
This issue doesn't seem actionable any more. We fully implement RFC 9002 now, so any performance issues would be due to bugs. More likely, performance issues are related to UDP handling.
