### ISSUE TITLE
Client issues too many CIDs when client resumes 0-RTT session and client set (*Config).ConnectionIDLength

### ISSUE THREAD

**Issue by rip-create-your-account** [lucas-clemente/quic-go#3057]
For me the following diff is enough to make the 0-RTT tests fail. The server sends `CONNECTION_ID_LIMIT_ERROR`.

``` diff
diff --git a/integrationtests/self/zero_rtt_test.go b/integrationtests/self/zero_rtt_test.go
index 3ab95efb..c98eca6f 100644
--- a/integrationtests/self/zero_rtt_test.go
+++ b/integrationtests/self/zero_rtt_test.go
@@ -93,7 +93,11 @@ var _ = Describe("0-RTT", func() {
                                sess, err := quic.DialAddrEarly(
                                        fmt.Sprintf("localhost:%d", proxyPort),
                                        clientConf,
-                                       getQuicConfig(&quic.Config{Versions: []protocol.VersionNumber{version}}),
+                                       getQuicConfig(
+                                               &quic.Config{
+                                                       Versions:           []protocol.VersionNumber{version},
+                                                       ConnectionIDLength: 4,
+                                               }),
                                )
                                Expect(err).ToNot(HaveOccurred())
                                str, err := sess.OpenUniStream()
```

It seems that `(*connIDGenerator).SetMaxActiveConnIDs` is first called for the resumed 0-RTT params, then for a second time when the params from the server are received. Every time that function is called it issues new CIDs.

**Comment by marten-seemann** [comment]
That's a funny bug. It occurs we call `SetMaxActiveConnIDs` twice when doing 0-RTT: https://github.com/lucas-clemente/quic-go/blob/2c45f2b11db0ceb1e6d8bc9cd668f27f5dde8b00/conn_id_generator.go#L56-L72
The first when we restore the transport parameters we remembered from the old connection, and once when we receive the transport parameters for the new connection.

It only occurs when we use non-zero-length CIDs, because there's no need to issue any CIDs when they're 0 bytes long anyways.

Thanks for reporting!
