### ISSUE TITLE
pointers for implementing the client

### ISSUE THREAD

**Issue by progrium** [lucas-clemente/quic-go#310]
I'd like to try implementing a client, but I can't tell how much of the session code is going to work or needs to change. It looked almost as if a client API just needs to wrap the rest of the protocol / session code, but I figured I would ask first before digging too deep.

**Comment by lucas-clemente** [comment]
First of all, thanks for wanting to help out 👍

We definitely want to add client support in the near future, and I think this is a good time to discuss what needs to be done. The majority of the code shouldn't be affected, but there's some things that go into establishing a connection that are quite different between server and client.

The things that come to my mind right now are:

- Support for client side crypto / handshaking
  - CHLO writing
  - Source-address-token handling
  - Cert validation
  - Key derivation / Diversification nonce handling
  - Probably some race-prone handling of different encryption levels
- Improved handling of streams (even vs odd IDs), mostly in `streams_map.go`
- HTTP, preferably as `http.RoundTripper` implementation, also have a look at `http.Transport`
- API for client, maybe use this chance to improve the encapsulation of the network-related stuff into one interface
- Ping frame sending (to keep the connection open)

Some of these things should be quite simple, but I think the crypto / handshaking part will take a bit more work since it's currently quite server-specific.

We're currently working through a ["bugfix / performance milestone"](https://github.com/lucas-clemente/quic-go/milestone/5), but I can start having a look at some of the crypto & handshake things next week. Let me know if some of these or the other tasks sound feasible to you. For more detailed discussions, I would suggest opening issues for the individual tasks :)

Maybe a good starting point for hacking around a bit is our (quite cobbled-together) [benchmark test](https://github.com/lucas-clemente/quic-go/blob/master/benchmark_test.go), where we link up two sessions to talk to each other.

**Comment by Lesterpig** [comment]
The missing client is the only thing that prevent me for using this package :smile: 

I would be very happy to help on that part.

**Comment by joeblew99** [comment]
A client in 100% golang would be really interesting to me.
I do allot of gomobile stuff these days and am itching to try out using QUIC on mobile. With it being 100% golang it makes life easier with cross device suppot etc too.
The other thing is to try it out with Webrtc.

**Comment by lucas-clemente** [comment]
There's probably gonna be news on the client soon :)

**Comment by joeblew99** [comment]
:) THis is really going to get interesting...

I am wondering how your planning to handle FEC (Forward Error Correction).
I guess it uses the 10:1 ratio where it sends enough info to reconstruct
any missed packets ?
I was thinking about using a message bus ( like NATS) with my mobile apps
and servers. Ironically the message bus's job is to do store and forward,
which is another way of solving missed packets, but its about missed
messages and so at a higher level of the stack literally.
But it does get you thinking - with no reliance on a kernel the logical
stack you build becomes less tiered and formal.....

Anyway, if you have any info on FEC with golang love to read it.

I guess no one has tried to compile the current code wth gomobile ?

**Comment by lucas-clemente** [comment]
Re FEC: That was removed from QUIC for now, see [this explanation](https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/Z5qKkk2XZe0) (and the link therein). If it's added back to QUIC at some point, we will look into supporting it.

Re gomobile: I don't think anybody has tried that yet. If you want, feel free to try it out and open issues if something doesn't work.

Also, let's keep the discussion here focussed on the client. If you have any other questions, just open a new issue :)

**Comment by joeblew99** [comment]
Ok i will try out mobile and raise issues i hit... cheers

**Comment by Skilgarriff** [comment]
Any update on this? I'm also really looking for the client implementation of quic, so if there is any direction I could be pointed in to help with this, I would love to help.

**Comment by marten-seemann** [comment]
Hi guys,

I've been working on a client implementation for the last couple of weeks (in the wip-client branch), sponsored by Protocol Labs.
At the moment, version negotiation, the crypto handshake for the client and simple GET requests should work, although there are still a lot of edge cases that I need to address. I think I'll make significant progress with this within the next two months.

I'll be very happy about real world feedback then!

Thanks,
Marten

**Comment by joeblew99** [comment]
i did not get a chance to run it on gomobile :( you knwo how it is. 

But looking forward to playing with the client @marten-seemann

**Comment by marten-seemann** [comment]
Hi everyone,

I just merged the *wip-client* branch into the master branch (see PR #399 for details). That means you can now start playing with the QUIC client! Have a look at the README for some basic instructions. 
I'd advise against using this in production code, since I expect there to be a bunch of (hopefully only smaller) issues. Furthermore, I'm not giving any guarantees regarding the client API at this point, so please expect it to change without prior notice.

That being sad, I'm very happy about any feedback, bug reports and bug fixes. Please just open a new issue here (or send me a PR) if you think that you found something!

**Comment by joeblew99** [comment]
i just did a update but am getting

../h2quic/request_writer.go:64: undefined: httplex.PunycodeHostPort

anyone else ?

**Comment by lucas-clemente** [comment]
Have you tried updating all dependencies? `go get -u github.com/lucas-clemente/quic-go`

**Comment by joeblew99** [comment]
yes i did that.

I just fix it with 
````

 go get -u golang.org/x/net

````

the readme advice did not do it for me:

````
go get -t did not work.

````

**Comment by Lesterpig** [comment]
Thanks a lot for your work! Do you have any additional documentation about how to use `quic.NewClient` and `quic.NewServer`? I do not manage to establish a working communication... 

https://godoc.org/github.com/lucas-clemente/quic-go

**Comment by marten-seemann** [comment]
Assuming you want to speak HTTP, you can use the API provided by the `h2quic` package: [https://godoc.org/github.com/lucas-clemente/quic-go/h2quic]().

For some simple examples, check out the [example directory](https://github.com/lucas-clemente/quic-go/blob/master/example/).

**Comment by pforemski** [comment]
Hi, and thanks so much for your work, guys! The QUIC client works for me @ https://github.com/pforemski/dingo/commit/e3f018df1fc377aba815af8817124c3a1949fa4a#diff-61906a9fecbd50a6152ff76633ea50f3

Do you have a quick advice on how can I separately control what the QUIC client sends in the SNI (Server Name Indication), in the HTTP/2 Host header, and the IP address it connects to? I need this for my project, where all these 3 parameters can be different. Thanks!

**Comment by Lesterpig** [comment]
@marten-seemann I'm mostly interested by *non-HTTP* protocols :stuck_out_tongue: 
I'll look h2quic, seems to contain a lot of interesting things, thanks!

**Comment by marten-seemann** [comment]
@pforemski: Can you please write us a new issue for that? I was expecting to make some changes there anyway, but I haven't had time to think about the details yet.

@Lesterpig: Which protocol are you planning to use over QUIC?

**Comment by Lesterpig** [comment]
@marten-seemann Home-made protocols, like sending raw protobuf messages (for more info check https://gitlab.com/SporeDB/sporedb/blob/master/myc/protocol/protocol.go)

I'm trying to use the Read/Write features provided by the streams, but in my case `client.OpenStream(3)` does not trigger server callback (probably because I'm not understanding go-quic's internals).

**Comment by marten-seemann** [comment]
@Lesterpig: I'm not sure I'm understanding the problem. Specifically, I don't know which server callback you're referring to.
In general, `client.OpenStream(3)` should open a new `utils.Stream` (have a look at the interface defined there). You can then do a `Stream.Write` (a `Stream` is an `io.Writer`). This should trigger a QUIC packet to be packed and sent on the wire.

If that doesn't work, please open a new issue and I'll have a look at it.
