### ISSUE TITLE
SentPacketHandler.OnLossDetectionTimeout sometimes called repeatedly during handshake

### ISSUE THREAD

**Issue by rip-create-your-account** [lucas-clemente/quic-go#3144]
I noticed irregular 100% CPU usage in a handshake test. Running the below command reproduces the issue for me roughly in 1/20 runs.

`ginkgo --focus "Handshake drop tests with QUIC version TLS dev version \(WIP\) when not using Retry using a long certificate chain: false client speaks first establishes a connection when 1/3 of the packets are lost in both direction"  --untilItFails`

I pinpointed the issue to `SentPacketHandler.OnLossDetectionTimeout` being called repeatedly. Logging the internal state during that call I noticed that when this happens `h.handshakeConfirmed` is always false and `h.appDataPackets.lossTime` is always set and always has the same value. From this I figured why the repeated calls are being made. The [check](https://github.com/lucas-clemente/quic-go/blob/3138a45fded18b7c15c12424ea662127b4b80c9f/internal/ackhandler/sent_packet_handler.go#L602) in `SentPacketHandler.OnLossDetectionTimeout` due to `h.handshakeConfirmed=false` stops `onVerifiedLossDetectionTimeout` from being called even though the `h.appDataPackets.lossTime` was reached. Then the loss detection timer is set to the exact same `h.appDataPackets.lossTime` value and the session wakes up for it, repeatedly.

**Comment by marten-seemann** [comment]
Interesting. This occurs when the packet containing the HANDSHAKE_DONE frame is lost, but an ACK for some of the 1-RTT packets is received. In that case, we might set an early retransmit timer (if not all 1-RTT packets up to the largest acknowledged packet were acked).

There are multiple ways to fix this. We could delay setting of the early retransmit timer for 1-RTT packets until the handshake is confirmed. This has the disadvantage that once the handshake is confirmed, it could happen that we immediately declare the packet lost (which is not wrong, we just missed the chance to send out the retransmission earlier, because we didn't set the timer).

Another solution is implementing the [optional way of declaring the handshake confirmed](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#name-handshake-confirmed):
> Additionally, a client MAY consider the handshake to be confirmed when it receives an acknowledgment for a 1-RTT packet. This can be implemented by recording the lowest packet number sent with 1-RTT keys, and comparing it to the Largest Acknowledged field in any received 1-RTT ACK frame: once the latter is greater than or equal to the former, the handshake is confirmed.
