### ISSUE TITLE
find an idiomatic way to associate a tracer with a connection

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#3145]
`quic.Listen` and `quic.Dial` both take a `quic.Config`. The `Config` has a [`logging.Tracer`](https://pkg.go.dev/github.com/lucas-clemente/quic-go@v0.20.1/logging#Tracer), which, if set, allows the application to return a `logging.ConnectionTracer`. Over the lifetime of the connection, quic-go emits a series of events, which can be traced by the connection tracer.

This is very helpful for generating metrics, and go-libp2p-quic-transport [uses](https://github.com/libp2p/go-libp2p-quic-transport/blob/master/tracer_metrics.go) it for this purpose.
The problem is, that it would be nice to associate application-layer information with that tracer. For example, it would be really helpful to also log the peer ID and the `AgentVersion`. This is not possible at the moment, since it's not possible to associate a tracer created by the `logging.Tracer.TracerForConnection` with the connection returned from `quic.Listen` or `quic.Dial`.

I'm wondering if there's an idiomatic way to solve this. @mvdan, do you have any idea?

**Comment by mvdan** [comment]
> This is not possible at the moment, since it's not possible to associate a tracer created by the `logging.Tracer.TracerForConnection` with the connection returned from `quic.Listen` or `quic.Dial`.

I'm not sure I follow. If I'm implementing TracerForConnection next to the application layer, can I not figure out what e.g. peerID to attach to a tracer I return, given the `p Perspective, odcid ConnectionID` parameters I'm given?

At least that's how I'd personally reason about this from the user's side. The tracer is for a single connection, and a single connection should generally have constant application-layer metadata to attach to traces.

**Comment by marten-seemann** [comment]
> If I'm implementing TracerForConnection next to the application layer, can I not figure out what e.g. peerID to attach to a tracer I return, given the p Perspective, odcid ConnectionID parameters I'm given?

That would require exposing the `odcid` to the application layer, which we currently don't have an API for. It would also be vulnerable to malicious clients, as the `odcid` is chosen by the client (although this attack might not be very interesting to begin with). Furthermore, it would require the application to keep a `map[ConnectionID]ConnectionTracer`. Certainly possible, but not a really nice solution.

**Comment by mvdan** [comment]
I see. But you do want to allow the application layer code to make an association with its metadata somehow, right?

In the world of tracing, the way one would generally solve this is by having incoming APIs like Listen or Dial take a context, then the application layer code can attach special tracing values to that context. Then, that same context is plumbed through to the tracing code, which can obtain and use those attached values.

You already seem to have that option with `Dial*Context` and `Listener.Accept`. I can show a rough example from the user's point of view if I'm not being clear.

**Comment by marten-seemann** [comment]
I see how this would work for `Dial*Context`: The user would attach values to the context, and we'd add a context to `logging.Tracer.TracerForConnection`. It feels a bit weird to me to use a context for things other than cancellations, but if that's the idiomatic way to solve this problem, I could live with that.
I struggle to see how this would work for `Listener.Accept` though.

If hacky solutions are on the table, one could also attach a value to the context returned by `Session.Context()`. That context is a fresh context created by the session constructor, and is closed as soon as the session is closed.

**Comment by mvdan** [comment]
Attaching values to contexts is not super performant, but it's pretty common for tracing as it tends to map well to the call stack, where you can add layered information that depends on the current context you're in. Plus, contexts themselves are layered, so it's helpful that it only keeps attached values for the lifetime of the nested context.

For most APIs it would be very difficult to attach tracing details at multiple levels without also passing some sort of tracing state, which would probably be worse than just using the context object.

I see how this would be difficult with Accept, though, as the Accept context is shared for many incoming connections. I did briefly think about this when I wrote the previous comment, but I was hoping you'd have a good alternative as a suggestion :)

> If hacky solutions are on the table, one could also attach a value to the context returned by `Session.Context()`. That context is a fresh context created by the session constructor, and is closed as soon as the session is closed.

That wouldn't work, I think, since contexts are layered. Attaching a value to that context would only affect the local scope, unless you pass the context back to quic-go in some way.

If you do pass it back, though, and that's pretty common, then I would agree that's how it should be done. Perhaps a bit verbose, but you do have to explicitly add your tracing metadata somewhere.
