### ISSUE TITLE
Is Chacha20Poly1305 supported?

### ISSUE THREAD

**Issue by wendigo** [lucas-clemente/quic-go#331]
I can see that DeriveKeysChacha20 is now commented out. 

README states that Chacha is supported.

**Comment by wendigo** [comment]
btw. Chacha20 implementation just landed in golang's tip: https://github.com/golang/go/commit/67d8226b4862f0f8deb4dc6fa8617017ecb0f32b

**Comment by lucas-clemente** [comment]
We have disabled ChaCha in the past due to problems with the repo we depend on. Since it has now landed in go, this is not relevant anymore :) However, there's a small difference in how QUIC uses ChaCha that will require us to fork the stdlib's package. Not a big issue though.

The main issue here is that we need to properly negotiate with the client whether we want to use AES or ChaCha. We have an issue (with a somewhat misleading title) #201.

Does this answer your question? If yes, I'd like to close this issue and track future work on negotiation in #201 :)

**Comment by wendigo** [comment]
Yes, thank you 👍 

Btw. quic-go in caddy is awesome 😄

**Comment by lucas-clemente** [comment]
Happy to hear that :)
