### ISSUE TITLE
Implement public reset receiving

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#34]

**Comment by lucas-clemente** [comment]
Should we postpone this to 0.3? Not even sure how to trigger it ;)

**Comment by marten-seemann** [comment]
We're now ignoring all public reset packets (we're just logging them).

I'm not sure what the expected behavior is (for a server), I don't think the spec says anything about that. Before my 3 commits today, public reset packets would usually end up as undecryptable packets (and therefore effectively get ignored). Now, at least we're explicit about what we're doing (and we're not wasting any memory to save them).

**Comment by marten-seemann** [comment]
This discussion might be helpful: https://mailarchive.ietf.org/arch/msg/quic/34g38ycklOuukgodQs6AfLfwHC0
