### ISSUE TITLE
Why is tls mandated for quic?

### ISSUE THREAD

**Issue by zhiqiangxu** [lucas-clemente/quic-go#3466]
IMO there're use cases for non-tls situation, like in inner network ?

**Comment by davidfdzp** [comment]
AFAIK "there is no way to use QUIC without TLS" (https://www.smashingmagazine.com/2021/08/http3-core-concepts-part1/)

**Comment by saleyn** [comment]
There's a lot of value in having an ability to disable TLS, so that quic-go can work with other QUIC clients (e.g. msquic) supporting this feature.

**Comment by marten-seemann** [comment]
No, there really is not. There's a lot of value in having an always-encrypted transport.

Also note that https://datatracker.ietf.org/doc/draft-banks-quic-disable-encryption/ never moved past a -00 version and has now been archived.

**Comment by saleyn** [comment]
> No, there really is not. There's a lot of value in having an always-encrypted transport.

One doesn't negate the other.  Having a Go QUIC client talking to a C QUIC client in an on-premices private network without encryption that has a stringent low-latency requirement is a valid use-case, and it's regretful not to be able to benchmark a Go QUIC application in that setting.

**Comment by marten-seemann** [comment]
I disagree. Having an unencrypted code-path in an implementation that’s used over the public internet is a foot gun. This applies even more so since there isn’t even a standardized way to do so (just to be clear, quic-go wouldn’t implement such an extension, even if there was one, for the reasons outlined above). If you want to do local benchmarking, feel free to fork the library and implement an unencrypted mode.

**Comment by saleyn** [comment]
There's no disagreement that using unencrypted mode on public internet is a strong no.  The feature I am after is to be able to use the quic-go in a fully private local network that contains latency-sensitive components written in C++ communicating through `msquic`.  We'd like to be able to use go.  Having to fork and maintain quic-go for that matter is a major inconvenience.
