### ISSUE TITLE
ConnectionState.SupportsDatagrams return wrong value

### ISSUE THREAD

**Issue by TNQOYxNU** [lucas-clemente/quic-go#3505]
I'm using quic-go v0.28.1 with go1.18.1 on Ubuntu 22.04.

When disable datagram on both server and client, `quic.Connection.ConnectionState().SupportsDatagrams` still report true, calling `quic.Connection.ReceiveMessage()` cause nil pointer dereference.

When error happened, `connection.peerParams.MaxDatagramFrameSize` is 0.

Test code:

```go
func TestDemo(t *testing.T) {
	server, err := quic.ListenAddr("127.0.0.1:12345",
		&tls.Config{
			Certificates: []tls.Certificate{selfSignedCert},
			NextProtos:   []string{"test"},
		},
		&quic.Config{EnableDatagrams: false})
	if err != nil {
		t.Error(err)
	}

	lock := &sync.Mutex{}
	lock.Lock()
	go func() {
		conn, err := server.Accept(context.Background())
		if err != nil {
			t.Error(err)
		}
		if conn.ConnectionState().SupportsDatagrams == true {
			t.Log("conn support datagram")
			t.Fail()
		}
		lock.Unlock()
	}()

	client, err := quic.DialAddr("127.0.0.1:12345",
		&tls.Config{InsecureSkipVerify: true, NextProtos: []string{"test"}},
		&quic.Config{EnableDatagrams: false},
	)
	if err != nil {
		t.Error(err)
	}
	if client.ConnectionState().SupportsDatagrams == true {
		t.Log("client support datagram")
		t.Fail()
	}

	lock.Lock()
}
```

**Comment by marten-seemann** [comment]
Looks like this check also needs to check for a value of 0: https://github.com/lucas-clemente/quic-go/blob/8c0c481da1644f9934df399c50649d65967d7f22/connection.go#L726-L728.
According to https://datatracker.ietf.org/doc/html/rfc9221#section-3, a value of 0 means that datagram support is disabled.

We should also make sure to set the correct value (`protocol.InvalidByteCount`) in the `newConnection` and `newClientConnection` constructors, so that we don't even send the transport parameter if datagram support is disabled, so that this check here works: https://github.com/lucas-clemente/quic-go/blob/8c0c481da1644f9934df399c50649d65967d7f22/internal/wire/transport_parameters.go#L394-L396

@TNQOYxNU, do you want to submit a PR with these 2 fixes?

**Comment by TNQOYxNU** [comment]
https://github.com/lucas-clemente/quic-go/blob/8c0c481da1644f9934df399c50649d65967d7f22/connection.go#L726-L728

Should this also check local configuration? In my understanding, `s.peerParam` is copied from hpeer's handshake packet, when server enabled support and client disabled support, `s.peerParam.MaxDatagramFrameSize` will bigger than 0 on client, client will still report datagram is supported.

I tried following code but it cause http3 test fail.
```go
 func (s *connection) supportsDatagrams() bool { 
 	return s.peerParams.MaxDatagramFrameSize > 0 && s.config.EnableDatagrams
 } 
```
