### ISSUE TITLE
Add support of HTTP Proxies

### ISSUE THREAD

**Issue by wireguard-dev** [lucas-clemente/quic-go#3519]
Hey! It would be nice to add a http proxy.

**Comment by TNQOYxNU** [comment]
It's impossible, QUIC is based on UDP, HTTP proxy can't forward UDP at all.

**Comment by marten-seemann** [comment]
Duplicate of #3370?

**Comment by TNQOYxNU** [comment]
Just less than one day ago, IETF released a new RFC called [Proxying UDP in HTTP](https://datatracker.ietf.org/doc/rfc9298/), so it's possible just now, but I expect poor server support on this new feature due to it's age and complexity.

You can always use your own net.PacketConn in [quic.Dial](https://pkg.go.dev/github.com/lucas-clemente/quic-go#Dial).
