### ISSUE TITLE
Add send pacing

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#355]
We should implement pacing of sent packets, i.e. try to reduce us sending bursts of packets.

I think the best way to implement this is by returning a delay from the sentPacketHandler and using the existing timer in the session to delay sending.

See also https://github.com/quicwg/base-drafts/blob/master/draft-ietf-quic-recovery.md (search for pacing).

**Comment by lucas-clemente** [comment]
I'm adding the want-help label, but this is probably a more involved issue. Ping this issue for more details if you want to work on this.

**Comment by twdkeule** [comment]
Hi, 
I took a look at this, because it might influence my project. 
But I am confused what needs to be done. 
It seems easy to extend `congestion.cubicSender` and `congestion.SendAlgorithm` to implement the IETF's method but as far as I can see the `SendAlgorithm.TimeUntilSend()` is only used in tests.
Is `ackhandler.sentPacketHandler.SendingAllowed()` the place to integrate it?

**Comment by lucas-clemente** [comment]
Yes, I think adding the IETF calculation to the congestion controller should be fine.

Changing SendingAllowed to return a time.Time would work, but note that we still send non-retransmittable frames (ACKs) when sending is not allowed (see [here](https://github.com/lucas-clemente/quic-go/blob/master/session.go#L599)). I'm not sure what to do with that – we should avoid sending ACKs alone if we're just waiting for the pacer, but still send them if we're congestion limited. We do have code that delays ACKs so that they are less likely to be sent out alone, so that might be enough.

Anyway, the time returned from the congestion via sentPacketHandler can then be used to set the session's timer. #593 touched the timer last, maybe its diff is a good hint for how to do that (it's a bit tricky).

**Comment by twdkeule** [comment]
I already changed the `congestion` and `ackhandler` packages, but now that I have to integrate everything in `session.go` I don't know exactly how to proceed in `session.sendPacket()`: https://github.com/twdkeule/quic-go/blob/add-send-pacing/session.go#L586

The problem is `TimeUntilSend()` needs a packetLength and this is not always available. I get a length from  `ack.MinLength()` (but this breaks some unit tests with nul pointer dereferences) and a length from `DequeuePacketForRetransmission()`. But after the retransmission, when sending new packets I assume, I see no way of getting a packet length, besides from `packedPacket.raw`

**Comment by lucas-clemente** [comment]
The way we have implemented sending right now we require the signal of whether we can send or not before actually packing the packet. This is not something I'm eager to change, as it's quite critical code. I think for purposes of pacing just using a fixed packet size `protocol.MaxPacketSize` in the calculation should be fine, what do you think?

**Comment by lucas-clemente** [comment]
Oh, and feel free to open a WIP PR. I can't comment on your code right now.

Btw, I don't like adding a parameter to `maybeResetTimer` – I know it's a bit ugly, but can you call TimeUntilSend() there too? :)

**Comment by twdkeule** [comment]
But then it can never be called with the correct packet size?

**Comment by lucas-clemente** [comment]
We can always add that later, but for now I think it should be enough to use the default size.
