### ISSUE TITLE
Support go1.20

### ISSUE THREAD

**Issue by chenrui333** [lucas-clemente/quic-go#3630]
Go 1.20 is expected to be [released in February 2023](https://tip.golang.org/doc/go1.20), but I did not see any issue tracker for supporting it, thus creating one. Thanks!

**Comment by marten-seemann** [comment]
Thank you @chenrui333! The rc shipped way earlier than I expected. I'm planning to ship a quic-go version that build with the Go 1.20 rc towards the end of the month, or in early January.

**Comment by chenrui333** [comment]
That sounds good, thanks! :)

**Comment by kokes** [comment]
Adding a note about my tests against Go 1.20, in case someone runs into the same issue.

I tested my app against 1.20rc3 once this was merged in and saw a number of benchmarks to worsen by about 20%. Tried to isolate the issue for quite some time, but repeatedly failed to do so. Then I just exported profiles from those benchmarks and saw the crypto as totally different (see the two profiles attached below).

Turns out there was quite a bit of rewriting coming into 1.20, see e.g. [this commit](https://github.com/golang/go/commit/335e7647f53293eb320c1f069eaf0ff641810d6d) (which explicitly mentions a 20% perf gap) or [this series](https://github.com/golang/go/commits/7026a8a1a9aba58285b3cae215df04140245b6db/src/crypto/internal/bigmod). The 20% slowdown is also mentioned in this [accompanying blogpost](https://words.filippo.io/dispatches/go-1-20-cryptography/). This is all due to the RSA stack used in my test, there [might be some improvements in 1.21](https://github.com/golang/go/issues/57752). (I haven't tested it against ECDSA and I'm not sure how much that is affected.)

![1 20rc3](https://user-images.githubusercontent.com/8451755/213187803-6699a760-281b-443d-a5b2-4ed2af87373b.svg)
![1 19 2](https://user-images.githubusercontent.com/8451755/213187811-7aaf7631-3da6-4eef-ad28-ba82a487dfd9.svg)
