### ISSUE TITLE
Send public reset when receiving FHOL from client

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#411]

**Comment by Aron-Schats** [comment]
I keep on thinking that the right thing to do is not to advertise support for Q036.  As long as Chrome supports Q035, the drawback to current approach is that connections chosen for FHL2 experiment will fail (instead of all connections using Q035 and succeeding).  However, as soon as Chrome drops Q035 support, this becomes a "better than nothing" approach.

**Comment by marten-seemann** [comment]
Hi @Aron-Schats, I agree with you in principle. I'd rather skip version 36 completely instead of implementing this hack.
However, the problem is more severe than you described, because Chrome doesn't do version negotiation (yet?). That means as soon as Chrome decides to speak version 36 by default, quic-go would be unusable.
Furthermore, according to the Google QUIC team, the FHL2 experiment will only be activated in about 1% of all Chromes. Since Chrome is racing a QUIC and a TCP request anyway, the impact on the latency will be quite small for those 1%.

**Comment by Aron-Schats** [comment]
> However, the problem is more severe than you described, because Chrome doesn't do version negotiation (yet?).

I don't think this is correct.  Some time ago, I added command-line flags to proto-quic's server and client to specify versions explicitly (specifically to test the fallback mechanism) and the fallback worked as one would expect it to.

**Comment by marten-seemann** [comment]
I just tried it again. Chrome still keeps ignoring Version Negotiation Packets.

**Comment by Aron-Schats** [comment]
That's odd.  What happens -- does it just fail to connect?  If you run `quic_client --v=4` instead of Chrome, it may provide some clues.  Is it possible there is a bug in quic-go?

**Comment by marten-seemann** [comment]
I just edited the `SupportedVersions` in *protocol/version.go* such that version 36 is the only supported version. Still Chrome just keeps on sending packets with version 35.

**Comment by lucas-clemente** [comment]
I think Chrome and the quic_client have always behaved differently when it comes to version negotiation: The quic_client supports it but Chrome doesn't.

**Comment by Aron-Schats** [comment]
Interesting.  Perhaps, then, the better way to go is to send back a version negotiation packet with VERSION=Q035 if CHLO has FHL2=1 instead of public reset.  This way, if or when Chrome supports fallbacks, it can fall back.

**Comment by lucas-clemente** [comment]
I guess that would work, but tbh I'm not sure it's worth the effort. Chrome will always fallback to TCP (without additional latency cost due to the parallel connection) if a connection can't be established using QUIC. Also, it's probably unlikely that we'll see version negotiation in Chrome until after v36 has been retired.

Do you have a specific use-case where this fallback would be an issue?
