### ISSUE TITLE
implement deadlines for streams

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#514]
We should implement a `SetDeadline`, `SetReadDeadline` and `SetWriteDeadline` for `Stream`s, analogous to the `net.Conn` (https://golang.org/pkg/net/#Conn).

**Comment by marten-seemann** [comment]
Related question: Do we also need those kind of deadlines for the QUIC connection itself? I'd lean towards no, but haven't made up my mind yet.

**Comment by lucas-clemente** [comment]
We also should look into #410 when thinking about this.

**Comment by lucas-clemente** [comment]
Do we really need this on the stream level, or would a deadline for the connection also suffice?

For h2 e.g. this would map better to the existing deadlines (which are afaik all connection-wide).

**Comment by marten-seemann** [comment]
I'm not really sure how this would work on the connection. Do only STREAM frames count as a reads / writes or any activity on the UDP socket?

For streams, the definition would be very clear. I looked at some other stream multiplexers. Yamux has stream-level deadlines (https://godoc.org/github.com/hashicorp/yamux#Stream), for SPDY there are a couple of Go implementations, where one has stream-level deadlines (https://godoc.org/github.com/docker/spdystream#Stream, not properly implemented though) and two don't (https://godoc.org/github.com/shykes/spdy-go#Stream and https://godoc.org/github.com/amahi/spdy#Stream). The IPFS streams are defined with deadlines (https://godoc.org/github.com/libp2p/go-stream-muxer).

**Comment by lucas-clemente** [comment]
> I'm not really sure how this would work on the connection. Do only STREAM frames count as a reads / writes or any activity on the UDP socket?

I would say activity of the UDP socket, similar to the idle timeout but different timeouts in both directions. We need to answer this question for #410 anyway.

Why is this something that is better solved at the transport level, rather than at the application level? Again, h2 doesn't need this (the go stdlib doesn't support it). Is there a case where this cannot be done on the app layer when (if) an application needs it? Note that the idle state timeout must be implemented at the transport layer, because the application is generally not aware of packets not containing stream data.

You might want to raise this issue with the WG, since there would have to be a new error code for that. I'm assuming you want to send a RST_STREAM, not a CONNECTION_CLOSE if this timeout expires?

**Comment by marten-seemann** [comment]
The deadlines are purely local operations, nothing is sent on the wire when a deadline is reached.

If you set a read deadline, then every `Read` will unblock as soon as the deadline is reached and return a timeout error. When `Read` is called after the deadline, it will return the same error. Furthermore, you can set a new deadline at any time (also after one deadline expired).
The same logic applies to `Write`s. And `SetDeadline` is just a shortcut for calling `SetReadDeadline` and `SetWriteDeadline` with the same value.

**Comment by lucas-clemente** [comment]
I see, I didn't know the timeouts were local-only and don't affect the state of the connection. Then sgtm.

**Comment by marten-seemann** [comment]
This issue has a "solution" that would work with the `sync.Cond` in the stream: https://github.com/golang/go/issues/9578.
 I'm not sure it makes sense to do it the idio(ma)tic way here, afaik the `sync.Cond` is more performant than channels, and deadlines will be *very* rare compared to the other signaling that is going on.

**Comment by lucas-clemente** [comment]
I'm not a big fan of this solution, I'd rather prefer to replace the cond as Ian suggested in the linked issue.

Also: We're already seeing the timers in profiles as we make heavy use of them in the session – and that's one per connection, not one per stream being read / written. We should be careful to profile any solution to make sure we don't regress performance.

**Comment by AudriusButkevicius** [comment]
Dialing, accepting connections, accepting and establishing streams should also be timeoutable.

**Comment by lucas-clemente** [comment]
Dialing and accepting is essentially the same thing (the handshake timeout). Since that is global for a quic listener or client, I'd prefer to have that in quic.Config. Initiating a stream is always guaranteed to succeed by the protocol and doesn't require a confirmation from the peer, so there's no timeout.

Btw: This issue here is nothing DOS relevant (as the handshake timeouts e.g. are), it's purely an API question. If the connection times out, the stream read / write will always error (even without SetDeadline).

**Comment by AudriusButkevicius** [comment]
So just from the API perspective, I think you should try to satisfy https://golang.org/pkg/net/#Conn, which implies using .SetDeadline and not alienating people who expect connections to work that way.

**Comment by marten-seemann** [comment]
`SetReadDeadline` and `SetWriteDeadline` are purely local operation and that have nothing to do with a connection timeout (and `SetDeadline` is just a convenience function that is equivalent to calling both of them). They make sure that `Read` and `Write` calls return when the deadline expires. They don't have any effect on the connection (see my comment on Apr 11 for a demo on a TCP connection).
On a QUIC connection, there's no `Read` and `Write` on the connection itself, which is why the `net.Conn` interface is not suitable for us.

**Comment by AudriusButkevicius** [comment]
Ok. net.Listener doesn't seem to have .SetDeadline.
The last compelling case for deadlines on sessiom would be making it easier to change the deadline on a case by case basis, versus having to reach into the config to adjust the timeout.

**Comment by lucas-clemente** [comment]
We could think about adding deadlines to the server to make the handshake timeout configurable while the server is running, although I don't agree that the timeout is the best way of preventing DOS issues. A server can already slow acceptance of new connections with our current API if it feels overwhelmed.

About deadlines on sessions, the idle connection lifetime is negotiated as part of the QUIC handshake, so we can't change that later.

**Comment by AudriusButkevicius** [comment]
Sorry, I am unfamiliar with quic so my terminology sucks. I meant timeout on accepting/opening streams and not idle connection timeouts. Having to reach into the config to adjust that would suck.

**Comment by lucas-clemente** [comment]
As I said above: Initiating a stream is always guaranteed to succeed by the protocol and doesn't require a confirmation from the peer, so there's no timeout. There's nothing to timeout on there.

**Comment by lucas-clemente** [comment]
Or do you mean API wise? Essentially unblocking the AcceptStream and OpenStream APIs?

**Comment by AudriusButkevicius** [comment]
Yes, API wise. I mean if it's just dispatching packets and is guaranteed to never block (even due to congestion, full queues/channels or what not) then perhaps it's pointless. Yet you should still have timeouts for all other things that might block such as handshakes etc (but I guess this is just part of the Dial/Accept timeouts?)
