### ISSUE TITLE
Make integrationtests run without changing /etc/hosts

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#553]
We currently need devs to add "127.0.0.1 quic.clemente.io" to /etc/hosts. I really don't like this, partly because it makes the setup much more complicated, and since it burns my subdomain.

**Comment by marten-seemann** [comment]
I suggest postponing this until #537 is merged.

**Comment by marten-seemann** [comment]
The problem here are the tests with our quic-go client. We need to give it a URL to download, which must not be localhost.
It would be easy if we could use the `net.Resolver` (https://golang.org/pkg/net/#Resolver), but this was only added in Go 1.8, so our tests wouldn't run on Go 1.7.

**Comment by marten-seemann** [comment]
I'm not sure if the `net.Resolver` would work, since it is a struct. See the discussion in https://github.com/golang/go/issues/12503#issuecomment-267559596.

**Comment by marten-seemann** [comment]
I did some more research. The reason this doesn't work is that the `quic_client` doesn't send a SNI in its CHLO for localhost, and the `quic_server` doesn't accept localhost as a valid SNI. The culprit seems to be https://cs.chromium.org/chromium/src/net/quic/platform/impl/quic_hostname_utils_impl.cc?rcl=478229abf628ef29be1e14518ac991654e256605&l=16.

**Comment by marten-seemann** [comment]
This was fixed a while ago.
