### ISSUE TITLE
QUIC without HTTP semantics

### ISSUE THREAD

**Issue by pavan4** [lucas-clemente/quic-go#557]
I would like to use QUIC as transport protocol without the HTTP semantics

I checked the server code [main.go](https://github.com/lucas-clemente/quic-go/blob/master/example/main.go) which led me to [server.go](https://github.com/lucas-clemente/quic-go/blob/master/h2quic/server.go) inside h2quic package

Could I implement any exposed interfaces? Any pointers in this direction?

**Comment by lucas-clemente** [comment]
Yes, you can! All of our HTTP2 logic (in the h2quic package) is implemented on top of the base quic package. You can find the docs here: https://godoc.org/github.com/lucas-clemente/quic-go.

**Comment by lucas-clemente** [comment]
And, I forgot to add: Feel free to ask any questions, our doc is not as good as it should be and that will help us improve :)

**Comment by pavan4** [comment]
I managed to get the 'server-side' of the setup but haven't quite understood how to setup the 'client-side' to connect and to the Listener. 

Specifically, I used the `quic.ListenAddr(addr, &config)` to listen and can see that the server is listening for udp connections. 

I checked the `h2quic` package to see how to code the client side using `quic.DialAddr` and `QuicRoundTripper` but haven't been successful yet. 

Any pointers to link the client side to reach specific server routes will be super helpful.

I am new to Go and learning it with this code. My apologies if this is super obvious from the documentation.

**Comment by lucas-clemente** [comment]
`quic.DialAddr` should be able to connect to the server. However, this is a bit tricky due to the certificates needed. You probably have to set `InsecureSkipVerify` in the `tls.Config` passed to `DialAddr` and pass a fake certificate to the server. Also, I don't think connecting to an IP or localhost will work.

I will try to write up a quick guide tomorrow. Also, check out @marten-seemann's https://github.com/marten-seemann/quic-conn (and in particular, [this integration test](https://github.com/marten-seemann/quic-conn/blob/master/integrationtests/integration_test.go)), which basically implements a TCP-like connection on top of QUIC. That might also give you some pointers.

**Comment by lucas-clemente** [comment]
I wrote a simple example for using QUIC without HTTP/2 in the PR linked above. Have a look and let us know if that helps :)

(The PR is set to close this issue, but please feel free to comment / reopen :)

**Comment by pavan4** [comment]
Great. I was working with quic-conn but this helps as well. Thank you so so much.

**Comment by pavan4** [comment]
I have used quic as an underlying transport protocol and have seen that with no packet loss quic performs significantly worse compared to tcp. When the packet loss increases quic performs better.

A few results [here](https://github.com/pavan4/benchmarking/tree/master/results/2017-07-08) 

It has been reported by other users as well : [results](https://github.com/maufl/quic_toy/blob/master/results/datarate-to-loss_10Mbps.png) 

Any reason this happens? Or quic was designed to get rid of HoL blocking, 0 RTT etc? 
Quic will be patched to fix this? Apologies, if this is not the right place to ask.
