### ISSUE TITLE
Don't send duplicate window update frames on retransmissions

### ISSUE THREAD

**Issue by lucas-clemente** [lucas-clemente/quic-go#689]
We currently have logic to not retransmit old windows updates. However, we retransmit window updates if they are still up to date, and add a new one as well. That leads to duplicate window updates for the same stream and offset:

```
1718944 15:59:54.690 -> Sending packet 0x2d131 (77 bytes) for connection c482fdeff40ed5eb, forward-secure
1718945 15:59:54.690  -> &frames.WindowUpdateFrame{StreamID:0x0, ByteOffset:0x3236d69}
1718946 15:59:54.690  -> &frames.WindowUpdateFrame{StreamID:0x0, ByteOffset:0x3236d69}
1718947 15:59:54.690  -> &frames.WindowUpdateFrame{StreamID:0x5, ByteOffset:0x323d95c}
1718948 15:59:54.690  -> &frames.WindowUpdateFrame{StreamID:0x5, ByteOffset:0x323d95c}
```

**Comment by marten-seemann** [comment]
I'm beginning to wonder if this optimization is really worth the effort.
To implement this, when sending a retransmission we'll have to scan the slice of WINDOW_UPDATEs that is send out using the regular code path, if they contain one WINDOW_UPDATE for the corresponding stream, and if so, we can cancel the retransmission. Performancewise this should only be relevant when we have a large number of streams and a small maximum flow control increment (so that the slice of WINDOW_UPDATEs is long), but still, it's even more complexity...

**Comment by marten-seemann** [comment]
I don't remember where this came from, but I just ran a download of a 50 MB file with 10% packet loss (so we got a lot of retransmissions of MAX_STREAM_DATA and MAX_DATA frames), and I didn't see any duplicates. Seems to have been fixed somewhere along the way.
