### ISSUE TITLE
Expose ConnectionState() to quic Session and h2quic Request handler

### ISSUE THREAD

**Issue by phuslu** [lucas-clemente/quic-go#746]
I intend to implement a SNI handler on top of h2quic.Server. 
Originally(means tls/http2), I could use  `req.TLS.ServerName` to identify the client's SNI.

For now, req.TLS in h2quic always is `nil`.

To get it work, seems that we need expose a method `ConnectionState()` in quic.Session and implement it in `cryptoSetup.HandleCryptoStream()` ? 

Is it a reasonable thought?

**Comment by lucas-clemente** [comment]
It seems reasonable to offer a way to get TLS infos from a session, but I'd like to wait until we actually use TLS 1.3. Otherwise this will stand in our way during the migration, and will need to be changed anyway.

In the meantime, can you use the Host header for your use case? Alternatively, you could maybe hook into the [tls config's GetCertificate](https://golang.org/pkg/crypto/tls/#Config) handler, but that doesn't carry information about the session.
