### ISSUE TITLE
Do you guys have any plan to implement BBR congestion control algorithm? I think it's an interesting and important algo.

### ISSUE THREAD

**Issue by jflyup** [lucas-clemente/quic-go#752]
[Here](https://cs.chromium.org/chromium/src/net/quic/core/congestion_control/bbr_sender.h) is the implementation by chromium.

**Comment by marten-seemann** [comment]
Yes, we've been planning this for a long time! BBR is a really interesting concept, and the performance measurements I've seen look really promising.
We already have an issue for that (#341) for quite a while, however, at the moment, we don't really have the time to implement that, since a bunch of other issues have a higher priority (especially the transistion to IETF QUIC).

**Comment by jflyup** [comment]
Thanks for the quick reply! Looking forward to that! Maybe I would go into this algo and try to implement  this on my own [reliable udp tunnel project](https://github.com/jflyup/ugo) if I'm free.

**Comment by lucas-clemente** [comment]
I had a look at this a while back, and there's a few changes we need to do for it. As Marten said, it's not a high prio for us right now, and there are easier performance wins right now.

Closing this as a duplicate of #341.
