### ISSUE TITLE
don't send an ACK for every packet received that just contains an ACK frame

### ISSUE THREAD

**Issue by marten-seemann** [lucas-clemente/quic-go#85]

**Comment by marten-seemann** [comment]
This is not as straightforward as it might seem. While it is ok (and desirable) to send an ACK only for every second packet that only contains an ACK frame, if we don't ack the last packet that we received (at the end of a connection), we would trigger a RTO.

**Comment by marten-seemann** [comment]
See `QuicConnection::MaybeQueueAck()` in `quic_connection.cc`.

**Comment by lucas-clemente** [comment]
Chrome seems to ACK either every second packet or after a timer `max(RTO/2, 25ms)` expires. This doesn't prevent an ACK-cascade, right?

Since 44acb8ca8210d14b8ba5c19672f94dfc568a384c, we delay ACKs for up to 5 ms (if we don't need to send a packet anyway). I'm not sure of the benefit of only ACKing every second packet when there's a timer anyway. Maybe we could simply set our timer to `max(RTO/2, 25ms)` as well and call this issue solved?

**Comment by lucas-clemente** [comment]
Closing this for #354.
