### ISSUE TITLE
Public Reset packets from Google do not contain RSEQ

### ISSUE THREAD

**Issue by Eichhoernchen** [lucas-clemente/quic-go#941]
Hi,

I can currently not use quic-go to connect to google.com.
Google seems to be sending Public RST packets which is odd in itself (I can also not connect via Chrome or the chrome test client so this must be something done intentionally by Google).
Yet, it seems that the packets (from Google) miss the RSEQ tag which causes quic-go to retry and finally fail with a "HandshakeTimeout" rather than acknowledging the Public RST.

Has the RSEQ been removed from the public reset packet? 
I seems to be missing in the test data in the chrome source?https://cs.chromium.org/chromium/src/net/quic/core/quic_framer_test.cc?rcl=f1d468e87426765c55bc7cd8194799e14267732d&l=5006

Thanks
 Jan

**Comment by marten-seemann** [comment]
Hello Jan,

yes, Google seems to have disabled QUIC at this moment. I noticed this some time last week, but unfortunately I don't have any further information about this. According to the gQUIC wire spec, RSEQ is a mandatory field on the Public Reset, but it looks like Google never (?) writes that value (see https://cs.chromium.org/chromium/src/net/quic/core/quic_framer.cc?type=cs&q=publicreset&sq=package:chromium&l=451). Assuming that their QUIC server implementation uses exactly the same code path, of course.

With IETF QUIC on the horizon, I don't care that much about the gQUIC spec anymore, and I think we should just parse packets without the RSEQ tag as well, so that connection establishment fails immediately (and you don't need to wait for the handshake timeout). I'll prepare a PR.

**Comment by Eichhoernchen** [comment]
Hi,

thanks for the quick reply.
I guess I'll just close the issue given the PR.

Thanks
